src/AbstractSyntaxTreeNode.ts, src/Mutant.ts, src/Mutator.ts, src/ReporterFactory.ts, src/Stryker.ts, src/TestFile.ts, src/TestResult.ts, src/TestRunnerFactory.ts, src/mutations/BaseMutation.ts, src/mutations/BaseOperatorMutation.ts, src/mutations/RemoveConditionalsMutation.ts, src/reporters/ConsoleReporter.ts, src/utils/FileUtils.ts, src/utils/ParserUtils.ts, src/utils/TypeUtils.ts, test/unit/MutantSpec.ts, test/unit/StrykerSpec.ts
Fixes #23 
The TestRunner folder (including the tests) has been skipped due to work on #27 on the branch 'api'
=> Removed _ in front of private variables and functions

Gruntfile.js, package.json, src/api/core/StrykerOptions.ts, src/api/test_runner/RunResult.ts, src/isolated-runner/IsolatedTestRunnerAdapter.ts, src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts, src/isolated-runner/Message.ts, src/isolated-runner/ResultMessageBody.ts, src/isolated-runner/RunMessageBody.ts, src/isolated-runner/StartMessageBody.ts, src/karma-runner/KarmaTestRunner.ts, test/integration/isolated-runner/DirectResolvedTestRunner.ts, test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts, test/integration/isolated-runner/NeverResolvedTestRunner.ts, test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts, typings/sinon-chai/sinon-chai.d.ts, typings/sinon/sinon.d.ts
Added the `IsolatedTestRunnerAdapter` with the ability to run a test runner in isolation (child process). Handles timeouts
Solve issue #30
=> Isolated test runner adapter

src/api/mutant.ts, src/api/mutant/Mutation.ts, src/api/mutant/Mutator.ts
=> Added an api for applying mutations

src/Stryker.ts
Old logging:
```
ERROR: One or more tests failed in the inial test run!
```
New logging:
```
ERROR: One or more tests failed in the inial test run:
C:\Users\myuser\Documents\workspace\myproject\test\module.global.js
C:\Users\myuser\Documents\workspace\myproject\test\mock\random.mock.js
```
=> Tests that failed during the initial test run are now logged

package.json, src/karma-runner/KarmaTestRunner.ts
Made karma-test-runner make use of the new in-memory reporter. Saves precious io time
=> In memory coverage

src/MutantRunResultMatcher.ts, src/api/test_runner/Coverage.ts, test/unit/MutantRunResultMatcherSpec.ts
=> All Coverage 'map types' are now indexed with a string

.vscode/launch.json, src/Stryker.ts, src/TestRunnerOrchestrator.ts, src/api/test_runner/RunResult.ts, src/karma-runner/KarmaTestRunner.ts, test/integration/karma-runner/KarmaTestRunnerSpec.ts, test/sampleProject/src/Error.js, test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
* Altered the test run api: added an errorMessages array to collect the error message
* Altered the karma test runner to make sure it defaults to Complete
* Altered Stryker to console log the new errorMessages
Resolve issue #64
New output when running with a test project using angular:
```bash
INFO: Running initial test run
ERROR: test iteration 0 resulted in an error
ERROR: ReferenceError: Can't find variable: angular
at http://localhost:1234/base/app/scripts/app.js?495cda078cd1e18758ce5603c54f15af926b77fb:9
```
=> (fix) added a notification for when a test failes in initial run.

.vscode/launch.json, README.md, package.json, src/InputFileResolver.ts, src/Stryker.ts, src/TestRunnerOrchestrator.ts, src/api/core.ts, src/api/core/InputFile.ts, src/api/test_runner/RunnerOptions.ts, src/jasmine_test_selector/JasmineTestSelector.ts, src/karma-runner/KarmaTestRunner.ts, src/utils/FileUtils.ts, test/integration/install-module/module/usingStryker.js, test/integration/install-module/module/usingStryker.ts, test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts, test/integration/karma-runner/KarmaTestRunnerSpec.ts, test/unit/InputFileResolverSpec.ts, test/unit/TestRunnerOrchestratorSpec.ts, test/unit/api/TestRunnerSpec.ts, test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts, typings/glob/glob.d.ts, typings/minimatch/minimatch.d.ts
Added a feature to choose the order of files. The stryker API is not 
```bash
Stryker -f <files> -m <filesToMutate> [other options]
```
You can use file globbing in the files and filesToMutate.
resolve issue #66
=> Feature choose order of files

src/isolated-runner/IsolatedTestRunnerAdapter.ts
=> (fix) Cleanup unused timeout timers

src/Stryker.ts, test/unit/StrykerSpec.ts
Added logging in Stryker.ts for when errors occur during initial test run. Also added a unit test for it. We still need to add more unit tests  for the stryker class (the unit test file was commented out)
=> (fix-errors-not-reported) Added logging for errors during inital test run

src/TestRunnerOrchestrator.ts, src/reporters/ConsoleReporter.ts, test/unit/TestRunnerOrchestratorSpec.ts
=> Uncovered mutants are no longer being tested

src/api/core/Factory.ts, src/api/mutant/Mutator.ts, src/api/test_runner/Coverage.ts, src/api/test_runner/RunOptions.ts, src/api/test_runner/RunResult.ts, src/api/test_runner/RunnerOptions.ts, src/api/test_runner/TestResult.ts, src/api/test_runner/TestRunner.ts, src/api/test_runner/TestRunnerFactory.ts, src/api/test_selector/TestSelector.ts, src/api/test_selector/TestSelectorFactory.ts, src/api/test_selector/TestSelectorSettings.ts, src/api/util/StrykerTempFolder.ts
I have documented the API.
@nicojs Could you review this?
Fixes #36
=> Added API documentation

CONTRIBUTING.md
Add the contributing guide
@wmeints @simondel  please both review :)
=> Feature contributor guide

src/isolated-runner/IsolatedTestRunnerAdapter.ts
Add ears on child process to prevent it from dying because the stream overflows
=> fix(IsolatedTestRunner) Add ears on child process

src/Stryker.ts, test/unit/StrykerSpec.ts
* A rejection now actually results in a rejection
* Stryker is resolved when everything went according to plan (but might contain survived mutations)
=> fix(stryker) Correct the promise resolving.

Gruntfile.js, README.md, package.json, src/ConfigReader.ts, src/PluginLoader.ts, src/Stryker.ts, src/api/config.ts, src/api/config/Config.ts, src/api/config/ConfigWriter.ts, src/api/config/ConfigWriterFactory.ts, src/api/core/StrykerOptions.ts, src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts, src/utils/fileUtils.ts, src/utils/objectUtils.ts, test/helpers/log4jsMock.ts, test/helpers/registerChaiPlugins.ts, test/integration/config-reader/ConfigReaderSpec.ts, test/integration/config-reader/invalid.conf.js, test/integration/config-reader/syntax-error.conf.js, test/integration/config-reader/valid.conf.js, test/integration/install-module/Executor.ts, test/integration/install-module/install-module.ts, test/integration/install-module/module/.gitignore, test/integration/install-module/module/package.json, test/integration/install-module/module/stryker.conf.js, test/integration/install-module/module/usingStryker.js, test/integration/install-module/module/usingStryker.ts, test/unit/PluginLoaderSpec.ts, test/unit/StrykerSpec.ts, test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
Adding the config file feature
resolve #86
=> Feature read config

README.md, src/Stryker.ts, src/api/config/Config.ts, testResources/module/stryker.conf.js, testResources/sampleProject/stryker.conf.js
I removed `'jasmine'` and `'karma'` from the default config and documented the options testFramework and testRunner.
=> Manual testFramework and testRunner configuration

.bithoundrc
I added a bithound config to make bithound use tslint instead of jslint.
**NOTE:** I may have to edit the config with some more commits.
=> Add bithound config

.vscode/launch.json, package.json, src/reporters/ClearTextReporter.ts
=> feat(ClearTextReporter) Log every mutant

src/TestRunnerOrchestrator.ts
Initialize test runner also in initial test run.
=> fix(TestRunnerOrchestrator): Initial test run

.gitattributes
See https://help.github.com/articles/dealing-with-line-endings/
After a pull: you can reset line endings locally to unix using these steps:
* Save your current files in Git, so that none of your work is lost.
```
git add . -u
git commit -m "Saving files before refreshing line endings"
```
* Remove every file from Git's index.
```
git rm --cached -r .
```
* Rewrite the Git index to pick up all the new line endings.
```
git reset --hard
```
=> fix(line-endings): Enforce unix line endings

src/mutators/BlockStatementMutator.ts, src/utils/parserUtils.ts, test/unit/mutators/BlockStatementMutatorSpec.ts, test/unit/utils/parserUtilsSpec.ts
=> fix(BlockStatementMutator): Not mutate empty block

README.md
* Improve wording/English
* Fix broken links
* Add a "Mandatory" field to the command line options
=> docs(README.md): Various improvements

src/mutators/RemoveConditionalsMutator.ts, test/integration/install-module/install-module.ts, test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts, test/integration/isolated-runner/SlowInitAndDisposeTestRunner.ts, test/unit/mutators/RemoveConditionalsMutatorSpec.ts
Fixes #216 and #166 and the issue @avassem85 was having.
=> fix(RemoveConditionalsMutator) Support omitting for-loop condition

src/MutatorOrchestrator.ts, src/mutators/ArrayDeclarationMutator.ts, src/mutators/ArrayDeclaratorMutator.ts, test/integration/utils/fileUtilsSpec.ts, test/unit/mutators/ArrayDeclaratorMutatorSpec.ts, testResources/sampleProject/src/Array.js
This new mutator changes array declaration into empty arrays.
=> Feature(ArrayDeclarationMutator), add new mutator.

test/unit/mutators/LogicalOperatorMutatorSpec.ts
Add Unit test for LogicalOperatorMutator
=> Add Unit test for LogicalOperatorMutator

README.md, packages/stryker/README.md
To help people get started, I (in my opinion) clarified the files option.
=> docs(README): Clarify configuration

.bithoundrc, .travis.yml, package.json, packages/stryker-html-reporter/.vscode/launch.json, packages/stryker-html-reporter/package.json, packages/stryker-html-reporter/protractor.conf.js
Remove the automated ui tests for the html report from the build temporarily, until we can find a more stable solution
=> test(html-reporter): Remove protractor from build

package.json, packages/stryker-api/.vscode/launch.json, packages/stryker-api/.vscode/tasks.json, packages/stryker-api/testResources/module/package.json, packages/stryker-karma-runner/.vscode/settings.json, packages/stryker-karma-runner/.vscode/tasks.json, packages/stryker-karma-runner/src/KarmaConfigReader.ts, packages/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.ts, packages/stryker/src/mutators/ArrayDeclaratorMutator.ts, packages/stryker/src/mutators/BinaryOperatorMutator.ts, packages/stryker/src/mutators/BlockStatementMutator.ts, packages/stryker/src/mutators/BooleanSubstitutionMutator.ts, packages/stryker/src/mutators/LogicalOperatorMutator.ts, packages/stryker/src/mutators/RemoveConditionalsMutator.ts, packages/stryker/src/mutators/UnaryOperatorMutator.ts, packages/stryker/src/mutators/UpdateOperatorMutator.ts, packages/stryker/src/utils/StrykerTempFolder.ts, packages/stryker/src/utils/Task.ts, packages/stryker/test/unit/reporters/ProgressAppendOnlyReporter.ts
* The task api type of T (instead of `T | undefined`)
* Mutator api copy siganture
=> fix(ts-2.4): Fix type issues for typescript 2.4

package.json, packages/stryker-mocha-runner/src/MochaTestRunner.ts, packages/stryker-mocha-runner/src/StrykerMochaReporter.ts, packages/stryker-mocha-runner/test/integration/MochaTestRunnerSpec.ts, packages/stryker/src/Stryker.ts, packages/stryker/test/unit/StrykerSpec.ts
=> fix(MochaTestRunner): Exit with a warning if no tests were executed

packages/stryker-typescript/README.md, packages/stryker-typescript/src/TypescriptConfigEditor.ts, packages/stryker-typescript/test/integration/ownDogFoodSpec.ts, packages/stryker-typescript/test/unit/TypescriptConfigEditorSpec.ts
=> feat(typescript): Force no code quality compiler options

packages/stryker/src/coverage/CoverageInstrumenterStream.ts, packages/stryker/test/unit/coverage/CoverageInstrumenterStreamSpec.ts
Thanks to @razsiel for the awsome fix! He won a t-shirt with it :)
=> test(CoverageInstrumenterStream): Improve mutation score

tasks/.bettercodehub.yml
This should bring us up to a score of 10/10 again :)
=> fix(BetterCodeHub): Use component-depth 2

package.json, packages/stryker-html-reporter/test/ui/pageObjects/ResultTable.ts, packages/stryker-typescript/src/mutator/BinaryExpressionMutator.ts, packages/stryker/src/transpiler/MutantTranspiler.ts, packages/stryker/test/unit/SandboxPoolSpec.ts, packages/stryker/test/unit/SandboxSpec.ts, packages/stryker/test/unit/child-proxy/ChildProcessWorkerSpec.ts
* Remove unused variables
* Alter types for co- and contra variance
=> chore(ts 2.6): Support TypeScript 2.6

packages/stryker-typescript/package.json, packages/stryker-typescript/src/TypescriptConfigEditor.ts, packages/stryker-typescript/src/TypescriptTranspiler.ts, packages/stryker-typescript/src/helpers/tsHelpers.ts, packages/stryker-typescript/test/unit/helpers/tsHelpersSpec.ts
Add a version check to verify that version >=2.5 of typescript is installed
Closes #437
=> feat(typescript): Add version check

packages/stryker/src/utils/fileUtils.ts, packages/stryker/test/unit/InputFileResolverSpec.ts
=> fix(InputFileResolver): Presume .zip and .tar are binary files.

packages/stryker-javascript-mutator/package.json
=> fix(peerDependencies): Remove typescript as a peer dependency

packages/stryker/test/integration/isolated-runner/ResilientTestRunnerFactorySpec.ts
Change timeout from 10000 to 15000 for ResilientTestRunnerFactorySpec
=> test(timeout): Set higher timeout

package.json, packages/stryker/package.json
Removed types as they are a part of commander 2.12.x
=> chore(dependencies): Upgrade to commander 2.12.2

packages/stryker-karma-runner/src/KarmaTestRunner.ts
Fixes https://github.com/stryker-mutator/stryker/issues/569
=> Fix(testRunner): Make karma exit with a valid exit code.

packages/stryker/src/mutators/ES5Mutator.ts
=> fix(es5-mutator): Describe migration for users with plugins

packages/stryker-javascript-mutator/package.json
Add dependency to lodash as it was missing. Fixes #593
=> fix(javascript-mutator): Add missing dependency

packages/stryker/package.json, packages/stryker/src/initializer/NpmClient.ts
See https://github.com/Microsoft/typed-rest-client/commit/d0bff29a5536c12a6f430b0e6b1acedd9b791730
=> build(stryker): update requirement for typed-rest-client

package.json
Let's pin the version for now (red build)
=> build(ts): pin ts version 2.7

packages/stryker-karma-runner/src/KarmaTestRunner.ts, packages/stryker-karma-runner/test/unit/KarmaTestRunnerSpec.ts
=> fix(Plugins): don't override default karma plugins ('karma-*')

packages/stryker-webpack-transpiler/package.json, packages/stryker-webpack-transpiler/src/WebpackTranspiler.ts, packages/stryker-webpack-transpiler/test/integration/transpiler.it.ts, packages/stryker-webpack-transpiler/test/unit/WebpackTranspilerSpec.ts
=> fix(Input files): passthrough all input files

packages/stryker/README.md, packages/stryker/src/reporters/DashboardReporter.ts, packages/stryker/test/unit/reporters/DashboardReporterSpec.ts
Saw some typos in the dashboard reporter and stryker readme. Decided to fix them
=> fix(Dashboard reporter): fix typos

integrationTest/package.json, integrationTest/test/angular-project/package.json, integrationTest/test/angular-project/stryker.conf.js
=> test(Webpack): use Webpack 4 in integration test

packages/stryker-typescript/package.json, packages/stryker-typescript/test/integration/allowJS.it.ts, packages/stryker-typescript/testResources/allowJS/math.js, packages/stryker-typescript/testResources/allowJS/math.ts, packages/stryker-typescript/testResources/allowJS/tsconfig.json, packages/stryker-typescript/testResources/allowJS/useMath.js
=> test(Allow js): add integration test for mixing js and ts code

packages/stryker/src/initializer/StrykerConfigWriter.ts, packages/stryker/src/initializer/StrykerInitializer.ts, packages/stryker/src/initializer/StrykerInquirer.ts, packages/stryker/test/unit/initializer/StrykerInitializerSpec.ts
=> Added support for yarn installs to `stryker init`

packages/stryker-api/src/config/Config.ts, packages/stryker-api/src/core/StrykerOptions.ts, packages/stryker-api/testResources/module/useCore.ts, packages/stryker/README.md, packages/stryker/src/Sandbox.ts, packages/stryker/src/StrykerCli.ts, packages/stryker/src/config/ConfigReader.ts, packages/stryker/src/config/ConfigValidator.ts, packages/stryker/src/process/InitialTestExecutor.ts, packages/stryker/test/integration/config-reader/ConfigReaderSpec.ts, packages/stryker/test/unit/SandboxSpec.ts, packages/stryker/test/unit/config/ConfigValidatorSpec.ts
It should solve [Rename 'timeoutMs' config key to 'timeoutMS'](#860 )
=> feat(stryker config): rename config setting `timeoutMs` to `timeoutMS`

.vscode/settings.json, package.json, packages/stryker-html-reporter/test/integration/StrykerReportSpec.ts, packages/stryker-html-reporter/test/ui/fileReport.uiTest.ts, packages/stryker-jasmine-runner/test/integration/JasmineRunner.it.ts, packages/stryker-karma-runner/test/integration/KarmaTestRunner.it.ts, packages/stryker-mocha-runner/src/MochaTestRunner.ts, packages/stryker-typescript/package.json, packages/stryker-webpack-transpiler/test/unit/fs/InputFileSystemSpec.ts, packages/stryker/src/Sandbox.ts, packages/stryker/src/child-proxy/ChildProcessProxy.ts, packages/stryker/src/child-proxy/ChildProcessProxyWorker.ts, packages/stryker/src/config/ConfigValidator.ts, packages/stryker/src/reporters/BroadcastReporter.ts, packages/stryker/src/reporters/EventRecorderReporter.ts, packages/stryker/src/test-runner/TestRunnerDecorator.ts, packages/stryker/test/unit/config/ConfigValidatorSpec.ts, packages/stryker/test/unit/reporters/BroadcastReporterSpec.ts, packages/stryker/test/unit/reporters/EventRecorderReporterSpec.ts
I have removed a lot of ``any`` types as I fixed one function: ``isNumber`` where ``NaN`` could be an edge case. (I see Travis doesn't work, but i have tested it locally and no issue has been found [even on windows])
=> refactor: stricter types

integrationTest/package.json
Removes 120mb from our integration test
=> test(integration): Remove unused dependencies

packages/stryker-api/src/config/ConfigEditor.ts
=> docs(ConfigEditor): add documentation for the ConfigEditor interface

packages/stryker/test/helpers/producers.ts
=> fix: isPrimitive function repair

packages/stryker/src/input/InputFileResolver.ts, packages/stryker/test/helpers/producers.ts, packages/stryker/test/unit/input/InputFileResolverSpec.ts
Fixes https://github.com/stryker-mutator/stryker/issues/1072
=> fix stryker input: handle error from trying dirs from submodules

packages/stryker/README.md
Fixes: #1213 
Should be thorough, but please let me know if there's anything I missed.
=> docs(readme): Improve Stryker readme format

package.json, packages/stryker-javascript-mutator/package.json
Attempting fix for npm install failing.
=> Dependency changes

packages/stryker-karma-runner/package.json, packages/stryker-karma-runner/src/KarmaTestRunner.ts, packages/stryker-karma-runner/src/StrykerReporter.ts, packages/stryker-karma-runner/test/integration/KarmaTestRunner.it.ts, packages/stryker-karma-runner/test/unit/KarmaTestRunnerSpec.ts, packages/stryker-karma-runner/test/unit/StrykerReporterSpec.ts
=> feat(karma-runner): Support automatic port selection

packages/stryker-javascript-mutator/src/mutators/StringLiteralMutator.ts, packages/stryker-mutator-specification/src/StringLiteralMutatorSpec.ts, packages/stryker-typescript/src/mutator/StringLiteralMutator.ts, packages/stryker-typescript/test/unit/mutator/StringLiteralMutatorSpec.ts
=> fix(mutator): String literal mutator

integrationTest/test/command/verify/verify.ts, packages/stryker-javascript-mutator/src/mutators/ConditionalExpressionMutator.ts, packages/stryker-mutator-specification/src/ConditionalExpressionMutatorSpec.ts, packages/stryker-typescript/src/mutator/ConditionalExpressionMutator.ts
=> feat(Conditional expression mutator): Mutate conditional operators

packages/stryker-babel-transpiler/package.json
=> test(babel-transpiler): Improve mocha timeout

packages/typed-inject/README.md
=> Fix typo in typed-inject readme

packages/stryker-api/package.json, packages/stryker-babel-transpiler/package.json, packages/stryker-html-reporter/package.json, packages/stryker-jasmine-runner/package.json, packages/stryker-jasmine/package.json, packages/stryker-javascript-mutator/package.json, packages/stryker-jest-runner/package.json, packages/stryker-karma-runner/package.json, packages/stryker-mocha-framework/package.json, packages/stryker-mocha-runner/package.json, packages/stryker-typescript/package.json, packages/stryker-util/package.json, packages/stryker-vue-mutator/package.json, packages/stryker-wct-runner/package.json, packages/stryker-wct-runner/test/integration/WctTestRunnerIT.ts, packages/stryker-webpack-transpiler/package.json, packages/stryker/package.json
Temp fix for: https://github.com/istanbuljs/nyc/issues/973
=> test(nyc): Temporarily fix issue where nyc reports lower coverage

packages/stryker-jest-runner/package.json
=> chore(dev-deps): Reset jest dependency version to 13 (red on windows)

lerna.json, package.json, packages/babel-transpiler/package.json, packages/core/package.json, packages/grunt-stryker/package.json, packages/html-reporter/package.json, packages/jasmine-framework/package.json, packages/jasmine-runner/package.json, packages/javascript-mutator/package.json, packages/jest-runner/package.json, packages/karma-runner/package.json, packages/mocha-framework/package.json, packages/mocha-runner/package.json, packages/mutator-specification/package.json, packages/typescript/package.json, packages/vue-mutator/package.json, packages/wct-runner/package.json, packages/webpack-transpiler/package.json
Use rebase instead of squash merge plz
=> V1 update versions

packages/core/package.json, packages/html-reporter/package.json, packages/jasmine-framework/package.json, packages/jasmine-runner/package.json, packages/jasmine-runner/src/JasmineTestRunner.ts, packages/jasmine-runner/tsconfig.src.json, packages/jasmine-runner/tsconfig.test.json, packages/javascript-mutator/package.json, packages/jest-runner/package.json, packages/karma-runner/package.json, packages/mocha-framework/package.json, packages/mocha-runner/package.json, packages/typescript/package.json, packages/util/package.json, packages/util/test/unit/StrykerError.spec.ts, packages/vue-mutator/package.json, packages/webpack-transpiler/package.json
Re-enable check coverage, since it is fixed node@11.8
https://nodejs.org/en/blog/release/v11.8.0
=> test(nyc): re-enable check coverage

packages/core/src/initializer/presets/AngularPreset.ts, packages/core/src/initializer/presets/ReactPreset.ts, packages/core/src/initializer/presets/VueJsPreset.ts, packages/core/test/unit/initializer/Presets.spec.ts
=> fix(presets): install v1.x dependencies instead of v0.x

.travis.yml
See https://github.com/facebook/create-react-app/issues/6591
=> build(travis): pin node version to 11.10

packages/core/src/SandboxPool.ts, packages/core/test/unit/SandboxPool.spec.ts
=> fix(clean up): prevent sandbox creation after dispose

packages/html-reporter/src/templates/index.html
=> fix(html): set utf-8 charset

package.json, packages/core/src/SourceFile.ts, packages/core/src/logging/LogConfigurator.ts, packages/core/src/mutants/MutantTestMatcher.ts, packages/core/test/unit/reporters/ClearTextReporter.spec.ts, tslint.json
Now you can choose whatever naming convention for variables and files do you want
=> tslint: match basarat styleGuide (#1594)

.github/ISSUE_TEMPLATE/maintenance.md
=> feat: add maintenance issue_template

packages/typescript/src/TypescriptMutator.ts, packages/typescript/test/unit/TypescriptMutator.spec.ts
=> fix(#1647): do not mutate `interfaces`

e2e/test/jest-react/package.json, e2e/test/jest-react/src/utils.js, packages/core/package.json, packages/core/src/ScoreResultCalculator.ts, packages/core/src/config/ConfigReader.ts, packages/core/src/di/PluginLoader.ts, packages/core/src/initializer/StrykerConfigWriter.ts, packages/core/src/reporters/ClearTextScoreTable.ts, packages/core/src/utils/objectUtils.ts, packages/core/test/unit/process/MutationTestExecutor.spec.ts, packages/core/test/unit/reporters/ClearTextScoreTable.spec.ts, packages/javascript-mutator/package.json, packages/javascript-mutator/src/helpers/copy.ts, packages/webpack-transpiler/package.json, packages/webpack-transpiler/src/compiler/ConfigLoader.ts
resolves issue #1795
Hi, I've removed lodash dependency with native lang features where considered reasonable, elsewise replaced whole lodash library dependency for dependencies on selective single functions.
=> refactor: remove lodash dependency (resolves issue #1795)

e2e/test/angular-project/verify/verify.ts, packages/wct-runner/package.json
=> test(e2e): allow flaky angular test for now

.gitignore, e2e/test/grunt-stryker-test/Gruntfile.js
=> test(e2e): improve grunt stability

packages/core/src/config/ConfigReader.ts, packages/core/test/integration/config-reader/ConfigReader.it.spec.ts, packages/core/testResources/config-reader/valid.json
featuring JSON file stryker config
It can be the first step to introduce schema for stryker (+ its nice feature I guess)
=> feat: support json-file config

packages/core/src/reporters/ci/GithubActionsProvider.ts, packages/core/src/reporters/ci/Provider.ts, packages/core/src/utils/objectUtils.ts, packages/core/test/unit/reporters/ci/GithubActionsProvider.spec.ts, packages/core/test/unit/reporters/ci/Provider.spec.ts
Add Github actions to the list of supported CI providers for the dashboard reporter
=> feat(core): add github actions ci provider

CONTRIBUTING.md
As discussed with @nicojs , ASTExplorer should be mentioned in the CONTRIBUTING file as it's very convenient to use while creating new features.
=> chore(readme): update contributing with astexplorer tool

packages/core/README.md, packages/core/src/StrykerCli.ts, packages/core/src/config/ConfigReader.ts, packages/core/src/input/InputFileCollection.ts, packages/core/src/transpiler/SourceMapper.ts, packages/core/test/integration/config-reader/ConfigReader.it.spec.ts, packages/core/test/unit/transpiler/SourceMapper.spec.ts, packages/core/testResources/config-reader/js/stryker.conf.js, packages/core/testResources/config-reader/json-and-js/stryker.conf.js, packages/core/testResources/config-reader/json-and-js/stryker.conf.json, packages/core/testResources/config-reader/json/stryker.conf.json, packages/core/testResources/config-reader/valid.conf.js, packages/mocha-runner/src/MochaTestRunner.ts, packages/mocha-runner/test/unit/MochaTestRunner.spec.ts, packages/wct-runner/src/WctTestRunner.ts, packages/wct-runner/test/unit/WctTestRunner.spec.ts, packages/webpack-transpiler/src/compiler/ConfigLoader.ts, packages/webpack-transpiler/test/unit/compiler/ConfigLoader.spec.ts
=> feat(json config): Load json config file if no js config file is present

packages/babel-transpiler/package.json, packages/grunt-stryker/package.json, packages/jasmine-framework/package.json, packages/jasmine-runner/package.json, packages/javascript-mutator/package.json, packages/jest-runner/package.json, packages/karma-runner/package.json, packages/mocha-framework/package.json, packages/mocha-runner/package.json, packages/typescript/package.json, packages/vue-mutator/package.json, packages/wct-runner/package.json, packages/webpack-transpiler/package.json
=> fix(Peer dependencies): set peer dependencies for v3

e2e/package-lock.json, e2e/package.json, e2e/test/angular-project/package-lock.json, packages/mocha-framework/package.json, packages/mocha-runner/package.json
Add official support for mocha 7 in `mocha-runner` and `mocha-framework`.
Fixes #2108
=> feat(mocha): support mocha 7

packages/api/package.json, packages/core/package.json, packages/typescript/package.json
=> fix(api): allow for different api versions of File

.github/workflows/ci.yml, .github/workflows/mutation-testing.yml, e2e/package-lock.json, e2e/package.json, e2e/test/jest-react/stryker.conf.js, package.json, packages/typescript/src/transpiler/TranspilingLanguageService.ts, packages/wct-runner/package.json
=> fix(ts): support ts 3.9 on windows in the typescript-transpiler

packages/core/test/helpers/setupMocha.ts, packages/instrumenter/src/printers/html-printer.ts, packages/instrumenter/src/printers/index.ts, packages/instrumenter/src/printers/js-printer.ts, packages/instrumenter/src/printers/ts-printer.ts, packages/instrumenter/src/util/syntax-helpers.ts, packages/instrumenter/test/helpers/factories.ts, packages/instrumenter/test/helpers/setupTests.ts, packages/instrumenter/test/helpers/stubs.ts, packages/instrumenter/test/integration/parser.it.spec.js.snap, packages/instrumenter/test/integration/parser.it.spec.ts, packages/instrumenter/test/integration/printers.it.spec.ts, packages/instrumenter/test/unit/parsers/html-parser.spec.ts, packages/instrumenter/test/unit/printers/html-printer.spec.ts, packages/instrumenter/test/unit/printers/js-printer.spec.ts, packages/instrumenter/test/unit/printers/ts-printer.spec.ts, packages/instrumenter/testResources/printer/echo/hello-world.html, packages/instrumenter/testResources/printer/echo/ts-with-comments.ts
Add printers for html, ts, vue and js files.
=> feat(instrumenter): add printers

packages/instrumenter/src/instrumenter.ts, packages/instrumenter/src/transformers/babel-transformer.ts, packages/instrumenter/src/transformers/html-transformer.ts, packages/instrumenter/src/transformers/index.ts, packages/instrumenter/src/transformers/mutant-collector.ts, packages/instrumenter/src/util/syntax-helpers.ts, packages/instrumenter/test/helpers/factories.ts, packages/instrumenter/test/helpers/stubs.ts, packages/instrumenter/test/integration/parsers.it.spec.js.snap, packages/instrumenter/test/integration/parsers.it.spec.ts, packages/instrumenter/test/integration/transformers.it.spec.js.snap, packages/instrumenter/test/integration/transformers.it.spec.ts, packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts, packages/instrumenter/test/unit/transformers/html-transformer.spec.ts, packages/instrumenter/test/unit/transformers/mutant-collector.spec.ts, packages/util/src/I.ts, packages/util/src/index.ts
Add transformers. Transformers are responsible for the process of generating mutants and placing them in the AST. 
* `htmlTransformer`: Capable of transforming html AST
* `babelTransformer`: Capable of transforming babel AST (JS and TS)
=> feat(instrumenter): add transformers

packages/api/schema/stryker-core.json, packages/babel-transpiler/package.json, packages/core/package.json, packages/core/src/test-runner/CommandTestRunner.ts, packages/core/test/integration/command-test-runner/CommandTestRunner.it.spec.ts, packages/core/test/unit/test-runner/CommandTestRunner.spec.ts, packages/grunt-stryker/package.json, packages/jasmine-framework/package.json, packages/jasmine-runner/package.json, packages/javascript-mutator/package.json, packages/jest-runner/package.json, packages/karma-runner/package.json, packages/mocha-framework/package.json, packages/mocha-runner/package.json, packages/test-helpers/package.json, packages/typescript/package.json, packages/vue-mutator/package.json, packages/wct-runner/package.json, packages/webpack-transpiler/package.json
=> fix(validation): don't warn about the commandRunner options

packages/core/package.json
=> fix: #2278

packages/instrumenter/src/mutators/arrow-function-mutator.ts, packages/instrumenter/test/unit/mutators/arrow-function-mutator.spec.ts
=> fix(ArrowFunction mutator): don't mutate () => undefined

packages/typescript-checker/README.md, packages/typescript-checker/src/fs/hybrid-file-system.ts, packages/typescript-checker/src/fs/script-file.ts, packages/typescript-checker/src/index.ts, packages/typescript-checker/src/plugin-tokens.ts, packages/typescript-checker/src/typescript-checker.ts, packages/typescript-checker/stryker.conf.js, packages/typescript-checker/test/integration/project-references.it.spec.ts, packages/typescript-checker/test/integration/single-project.it.spec.ts, packages/typescript-checker/test/integration/typescript-checkers-errors.it.spec.ts, packages/typescript-checker/test/unit/fs/hybrid-file-system.spec.ts, packages/typescript-checker/test/unit/fs/script-file.spec.ts
Log whenever a file is being watched.
=> chore(typescript-checker): improve logging

packages/instrumenter/src/parsers/index.ts, packages/instrumenter/test/integration/parsers.it.spec.js.snap, packages/instrumenter/test/integration/parsers.it.spec.ts, packages/instrumenter/testResources/parser/app.cjs, packages/instrumenter/testResources/parser/app.mjs
=> fix(parser): add support for `.mjs` and `.cjs` file formats

packages/core/src/input/InputFileResolver.ts
Support emojis and other encoded characters in file names when using git ls-files.
Port from Stryker v4 (https://github.com/stryker-mutator/stryker/pull/2430)
=> fix(input files): support emojis in file names

e2e/test/jasmine-ts-node/stryker.conf.json, packages/api/schema/stryker-core.json, packages/core/src/StrykerCli.ts, packages/core/src/di/buildMainInjector.ts, packages/core/test/unit/StrykerCli.spec.ts, packages/core/test/unit/config/OptionsValidator.spec.ts
=> feature(core): Adding `appendPlugins` commandline option

packages/jest-runner/README.md, packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts, packages/jest-runner/test/unit/configLoaders/ReactScriptsTsJestConfigLoader.spec.ts
=> feat(create-react-app-ts): deprecate support for create-react-app-ts projects

packages/typescript-checker/README.md
=> remove note from beta version

e2e/package-lock.json, e2e/package.json, package.json, packages/core/test/unit/sandbox/ts-config-preprocessor.it.spec.ts, packages/mocha-runner/src/mocha-adapter.ts, packages/mocha-runner/test/unit/mocha-adapter.spec.ts
Support Mocha >= 8.2 in the @stryker-mutator/mocha-runner. Solves "Type Error: TypeError: LibWrapper_1.default.loadRootHooks is not a function"
=> feat(mocha): support mocha 8.2

packages/core/src/reporters/html/templates/index.html
Position Stryker image on the bottom of the report
=> feat(html-report): reposition stryker image

packages/grunt-stryker/package.json, packages/jasmine-runner/package.json, packages/jest-runner/package.json, packages/karma-runner/package.json, packages/mocha-runner/package.json, packages/typescript-checker/package.json
Fixes #2606
We'll have to figure out how lerna could help automate this. Or add a check before versioning.
=> fix(peerDeps): update core in peerDependencies

.github/ISSUE_TEMPLATE/maintenance.md
fixes: #2620 
I hope this will work :c
=> main: fix maintenance template

MAINTAINERS.md
=> docs: add MAINTAINERS.md

docs/jest-runner.md
Just a tiny update.
BTW, thanks for the awesome tool!
=> docs: remove extra ]

docs/guides/angular.md, docs/guides/nodejs.md, docs/guides/react.md, docs/guides/vuejs.md, docs/sidebar.json, docs/troubleshooting.md
Add a general troubleshooting guide and point to that from each specific guide.
Closes #2722
=> docs(troubleshooting): add troubleshooting guide

packages/instrumenter/src/disable-type-checks.ts, packages/instrumenter/src/parsers/html-parser.ts, packages/instrumenter/src/parsers/index.ts, packages/instrumenter/src/parsers/ts-parser.ts, packages/instrumenter/src/printers/index.ts, packages/instrumenter/src/printers/ts-printer.ts, packages/instrumenter/src/syntax/index.ts, packages/instrumenter/src/transformers/babel-transformer.ts, packages/instrumenter/src/transformers/transformer.ts, packages/instrumenter/test/integration/disable-type-checks.it.spec.ts, packages/instrumenter/test/integration/instrumenter.it.spec.ts, packages/instrumenter/test/integration/parsers.it.spec.ts, packages/instrumenter/test/integration/parsers.it.spec.ts.snap, packages/instrumenter/test/unit/parsers/html-parser.spec.ts, packages/instrumenter/test/unit/parsers/ts-parser.spec.ts, packages/instrumenter/testResources/disable-type-checks/vue-tsx-sample.vue, packages/instrumenter/testResources/disable-type-checks/vue-tsx-sample.vue.out.snap, packages/instrumenter/testResources/instrumenter/vue-tsx-sample.vue, packages/instrumenter/testResources/instrumenter/vue-tsx-sample.vue.out.snap
=> fix(vue-tsx): support parsing tsx script in .vue file (issue#2849)

docs/guides/vuejs.md
Hi !
I have fixed the crossenv installation method of `docs/guides/vuejs.md`.
thx 😃
=> fix crossenv instalation method

docs/configuration.md, packages/core/src/input/input-file-resolver.ts, packages/core/test/unit/input/input-file-resolver.spec.ts
=> fix(ignore patterns): always ignore *.tsbuildinfo files

packages/core/src/config/config-reader.ts, packages/core/test/integration/config-reader/config-reader.it.spec.ts
=> docs(config reader): fix typo in warning message

.mergify.yml
See also: https://api.github.com/repos/stryker-mutator/stryker-js/pulls/3051
=> build: Set correct dependabot author

docs/troubleshooting.md
Add the example and solution for the decorator-legacy issue.
=> docs(troubleshooting): add decorator troubleshooting guide

packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts, packages/instrumenter/test/integration/instrumenter.it.spec.ts, packages/instrumenter/test/unit/mutant-placers/expression-mutant-placer.spec.ts, packages/instrumenter/testResources/instrumenter/optional-chains.ts, packages/instrumenter/testResources/instrumenter/optional-chains.ts.out.snap
=> fix(instrumenter): Handle TypeScript NonNullExpression

packages/core/src/initializer/stryker-config-writer.ts, packages/core/test/unit/initializer/stryker-initializer.spec.ts
=> feat(config): Add link to docs when generating a custom config

e2e/package.json, e2e/tasks/run-e2e-tests.ts
Whoopsy, turned off all but 1 e2e test 😨
=> chore(e2e): re-enable e2e

packages/core/src/reporters/clear-text-score-table.ts, packages/core/test/unit/reporters/clear-text-reporter.spec.ts
=> [solves #3315]: show n/a instead of NaN on clear-text report.

package.json
See https://github.com/lerna/lerna/issues/2822#issuecomment-834774899
=> chore(peerDeps): force legacy peer deps

packages/core/src/child-proxy/child-process-proxy-worker.ts, packages/core/src/child-proxy/child-process-proxy.ts, packages/core/src/child-proxy/message-protocol.ts, packages/core/test/unit/child-proxy/child-process-proxy.spec.ts
Remove the auto start magic string in favor of `require.main === module`.
=> refactor(child-process): remove auto start magic

packages/core/package.json, packages/core/src/logging/log-utils.ts, packages/core/test/helpers/producers.ts
See https://github.com/log4js-node/log4js-node/blob/master/CHANGELOG.md#640
Fixes #3373
=> build(deps): update log4js to 6.4

packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts
=> refactor(expression mutant placer): add returns

packages/jest-runner/package.json
=> chore(jest-types): fix type missmatch

docs/troubleshooting.md
Follow up to a Slack post: https://stryker-mutator.slack.com/archives/CTYUW4B0E/p1634123487026100.
Sorry that it took that long.
=> Added new description to troubleshooting.md

e2e/test/jest-react-ts/stryker.conf.json, perf/config/express/stryker.conf.json, perf/tasks/run-perf-tests.ts
Update the `express` git submodule to the latest master commit.
=> test(perf): update express performance test

packages/core/src/checker/checker-facade.ts, packages/core/test/unit/checker/checker-facade.spec.ts
Added tests for ```checker-facade.ts``` added with the 6.0 beta version. Got 100% mutation score and fixed a minor bug 😎.
Closes #3459
=> test(checker-facade): Added tests for checker-facade.ts

docs/config-file.md
=> Fix doc misspelling

e2e/package-lock.json, e2e/package.json, package-lock.json, package.json, packages/mocha-runner/package.json
mocha release mocha@10 to drop Node 12
https://github.com/mochajs/mocha/releases/tag/v10.0.0
=> fix: widen mocha peerDependencies Entry

packages/jest-runner/test/helpers/producers.ts
This should fix our CI pipeline
=> chore(ci): fix ci build for jest configuration

package.json
Update incremental mutation testing script with latest lerna release
=> test(ci): incremental mutation testing script

packages/api/src/report/reporter.ts
=> Update link to schema in report.ts

docs/configuration.md
=> docs: Add undocumented properties

docs/configuration.md, packages/api/schema/stryker-core.json, packages/core/src/process/3-dry-run-executor.ts, packages/core/src/stryker-cli.ts, packages/core/test/unit/config/options-validator.spec.ts, packages/core/test/unit/process/3-dry-run-executor.spec.ts, packages/core/test/unit/stryker-cli.spec.ts
A potential solution for [#4197](https://github.com/stryker-mutator/stryker-js/issues/4197)
=> Feat (config): Add --allowEmpty option

e2e/test/ignore-static/karma.conf.js, e2e/test/ignore-static/package.json, e2e/test/ignore-static/spec/math.tap.js, e2e/test/ignore-static/stryker.conf.json, e2e/test/ignore-static/verify/verify.js, e2e/test/ignore-static/verify/verify.js.snap, e2e/test/ignore-static/vitest.config.js, e2e/test/ignore-static/vitest.setup.js
Add vitest and tap to the ignore-static e2e test.
Closes #4112
Closes #4108
=> test(e2e): add vitest and tap to ignore-static

e2e/test/vitest-in-source-testing/package.json, e2e/test/vitest-in-source-testing/src/main.ts, e2e/test/vitest-in-source-testing/stryker.conf.json, e2e/test/vitest-in-source-testing/tsconfig.json, e2e/test/vitest-in-source-testing/verify/verify.js, e2e/test/vitest-in-source-testing/verify/verify.js.snap, e2e/test/vitest-in-source-testing/vitest.config.ts
=> test(vitest): add e2e test for vitest in-source testing

docs/incremental.md, docs/plugins.md, docs/sidebar.json, docs/tap-runner.md, docs/vitest-runner.md
Document the tap runner- and vitest runner plugins.
Closes #4221 
Closes #4220
=> docs(test runners): document `tap` and `vitest`

packages/vitest-runner/src/vitest-test-runner.ts, packages/vitest-runner/test/unit/vitest-runner.spec.ts
=> fix(vitest): allow `dispose` without `init`

docs/troubleshooting.md
Fix #3068
Document solution from [comment](https://github.com/stryker-mutator/stryker-js/issues/3068#issuecomment-1337272246) in troubleshooting page.
=> docs(troubleshooting): add solution for module-alias

docs/configuration.md, docs/tap-runner.md, docs/vitest-runner.md
Needed for https://github.com/stryker-mutator/stryker-mutator.github.io/pull/719
=> chore(docs): update docs

e2e/package-lock.json, e2e/package.json, package-lock.json, package.json, packages/jest-runner/src/jest-plugins/mixin-jest-environment.cts, perf/package-lock.json, perf/package.json
Support `handleTestEvent` as a custom class property (instead of method).
=> fix(jest-runner): support `handleTestEvent` class property

docs/configuration.md, packages/api/schema/stryker-core.json, packages/core/test/unit/config/options-validator.spec.ts, packages/core/test/unit/fs/project-reader.spec.ts, packages/instrumenter/src/parsers/create-parser.ts, packages/instrumenter/test/integration/parsers.it.spec.ts, packages/instrumenter/test/integration/parsers.it.spec.ts.snap, packages/instrumenter/testResources/parser/app.cts, packages/instrumenter/testResources/parser/app.mts, packages/tap-runner/src/setup/hook.cts, packages/tap-runner/stryker.conf.js
=> feat(instrumenter): support `.mts` and `.cts` file extensions

packages/core/src/initializer/npm-client.ts, packages/core/test/unit/initializer/stryker-initializer.spec.ts
=> fix(initialize): use correct url to fetch additional test runner config

docs/plugins.md
=> docs(plugins): Add json reporter

packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts, packages/instrumenter/testResources/instrumenter/mutant-placing.ts, packages/instrumenter/testResources/instrumenter/mutant-placing.ts.out.snap
Prevent trying to place mutants inside assignment expressions.
Fixes #4884
=> fix(mutant placement): don't place mutants inside assignment expression

packages/mocha-runner/src/mocha-test-runner.ts, packages/mocha-runner/test/unit/mocha-test-runner.spec.ts
=> fix(mocha-test-runner): test filter

e2e/package-lock.json, e2e/package.json, package-lock.json, package.json, packages/mocha-runner/package.json
Closes #5139
I run the tests for the plugin and also tested this with my projects use the plugin (with `mocha@11.0.1`).
=> feat: support mocha v11

packages/instrumenter/src/parsers/html-parser.ts, packages/instrumenter/test/integration/parsers.it.spec.ts, packages/instrumenter/test/integration/parsers.it.spec.ts.snap, packages/instrumenter/test/unit/parsers/html-parser.spec.ts, packages/instrumenter/testResources/parser/index-module.html
=> fix(instrumenter): Script tags with type "module" are not being mutated
