stryker-mutator/stryker-js

- src/MutantRunResultMatcher.ts
- src/karma-runner/KarmaTestRunner.ts
- test/unit/MutantRunResultMatcherSpec.ts
The correct tests are now matched with every Mutant. The MutantRunResultMatcher now looks for the smallest statement that covers a mutant. If this statement does NOT cover the mutant: then the mutant is not covered by this test.
There is an issue with Karma, it reports that a run has caused an error if every test failed. This caused mutants which were covered and killed by one test to be reported as 'untested'. I have solved this issue by checking if no test failed when determining if a run caused an error.
> Fixed too many tests being ran

- src/InputFileResolver.ts
- test/unit/InputFileResolverSpec.ts
Wrong order when globbing promisses resolve in different order.
> fix(InputFileResolver) Fix for potentially wrong order of files

- .travis.yml
- README.md
- package.json
Fixes #91 
Travis now builds the following node versions:
* 0.12.0 (lowest supported version)
* 4.x.x
* 5.x.x
The node version badge in the README will *probably* work after a new release.
> Lowest node version

- .vscode/launch.json
- README.md
- src/InputFileResolver.ts
- src/Mutator.ts
- src/Stryker.ts
- src/TestRunnerOrchestrator.ts
- src/isolated-runner/IsolatedTestRunnerAdapter.ts
- src/karma-runner/KarmaTestRunner.ts
- test/helpers/log4jsMock.ts
- test/integration/config-reader/ConfigReaderSpec.ts
- test/integration/install-module/install-module.ts
- test/unit/InputFileResolverSpec.ts
- test/unit/StrykerSpec.ts
* Replaced all console.log statements with log4js log statements
* Add some debug logging statements
* Pipe through the test runner output to `log.trace` method.
> Refactor logging

- .editorconfig
- Gruntfile.js
- package.json
* Remove typings, now done on npm pretest script
* Refactored the grunt serve task to now only run unit tests
> refactor(grunt) Remove 'typings' from grunt build

- package.json
- src/TestRunnerOrchestrator.ts
- src/api/util/StrykerTempFolder.ts
- test/unit/TestRunnerOrchestratorSpec.ts
- typings.json
Mocha requires Stryker to copy not only the source files, but also the test files.
This PR ensures that Stryker copies all files to the temp folder and that a directory structure is created which matches the original directory structure.
> Copy test files to the temp directory

- test/helpers/log4jsMock.ts
For the log4js mock, it is nessesery to restore it after each test run in order to clean in for the next one (if there is a next one)
> fix(log4jsMock): Restore sandbox in log4js mock

- bin/stryker
- package.json
- src/Stryker.ts
- src/stryker-cli.ts
- testResources/module/package.json
Refactor Stryker class to not include the cli. Also add stryker as bin so it can be used directly from an npm script (i.e. "stryker": "stryker --configFile stryker.conf.js")
> refactor(cli): Add stryker as binary

- src/TestRunnerOrchestrator.ts
- test/unit/TestRunnerOrchestratorSpec.ts
An error in a test run which was mutated now results in a killed mutant.
> fix(TestRunnerOrchestrator): Error in test run

- src/ReporterOrchestrator.ts
- src/reporters/BroadcastReporter.ts
- src/reporters/EventRecorderReporter.ts
- src/utils/fileUtils.ts
- test/integration/utils/fileUtilsSpec.ts
- test/unit/reporters/EventRecorderReporterSpec.ts
Add an event recorder reporter which can record events by writing there json representation to files, numbering them chronologically.
>  feat(event-recorder): Add event recorder reporter

- src/utils/parserUtils.ts
- test/unit/utils/parserUtilsSpec.ts
The parser utils is responsible to add id's to ast nodes. I add support for having properties which refer to the same part of the ast. This happens for example with a try catch:
http://esprima.org/demo/parse.html?code=try%7B%0D%0A%7Dcatch(error)%7B%0D%0A%7D
> fix(parserUtils): Add support for duplicate ast

- package.json
- src/TestRunnerOrchestrator.ts
- src/isolated-runner/IsolatedTestRunnerAdapter.ts
- src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts
- src/isolated-runner/Message.ts
- test/helpers/log4jsMock.ts
- test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
- test/integration/isolated-runner/SlowInitAndDisposeTestRunner.ts
- test/unit/TestRunnerOrchestratorSpec.ts
- test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
Add support for test runner lifecycle events: init and dispose. These are called once in every test runner life cycle (if implemented).  If they return a promise, we will wait for those promises to be resolved before proceding. We will only wait for max 2 seconds with the dispose before forcing the child process to be killed.
> feat(test-runner): Support lifecycle events

- src/Stryker.ts
- src/utils/StrykerTempFolder.ts
- src/utils/fileUtils.ts
- test/unit/StrykerSpec.ts
When running mocha tests, we need to be able to resolve the local node_modules. The way this works in npm is that it searches for a node_modules in de current working directory. If not found, check the dir above. Etc. By creating the tmp-folder's locally, node_,modules will be resolved as expected.
> fix(StrykerTempFolder): Use local tmp folder

- .gitignore
- .vscode/launch.json
- package.json
- src/InputFileResolver.ts
- src/Stryker.ts
- src/TestRunnerOrchestrator.ts
- src/stryker-cli.ts
- test/unit/InputFileResolverSpec.ts
- test/unit/StrykerSpec.ts
- test/unit/TestRunnerOrchestratorSpec.ts
- testResources/module/package.json
- testResources/sampleProject/stryker.conf.js
- typings.json
Add support for InputFileDescriptor object format instead of the string format in the `files` array . The object includes the `included` and `mutated` optional properties. Also updated the stryker-api version.
> feat(unincluded-files): Add support for unincluded

- .gitignore
- .vscode/launch.json
- package.json
- stryker.conf.js
It has been a long time comming, but we can now finally run stryker on stryker itself. :dog:. Add stryker-mocha-runner and stryker-html-reporter as dev dependencies. Add the stryker.conf.js used to run stryker.
> test(stryker): Eat own dogfood

- package.json
- src/isolated-runner/IsolatedTestRunnerAdapter.ts
- src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts
- src/utils/objectUtils.ts
- test/integration/isolated-runner/DiscoverRegexTestRunner.ts
- test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
- test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
* Add support for communicating regexes (and functions) from the stryker process to test runners running in child processes.
* Add dependency to 'serialize-javascript'. A minimalistic module for serializing regexes and functions in a json structure.
> fix(isolated-test-runner): Support regexes

- src/TestRunnerOrchestrator.ts
Added a logging statement to indicate that Stryker is busy with the initial test run
> Fix(TestRunnerOrchestrator) Mention the initial test run

- .vscode/launch.json
- src/Stryker.ts
- src/utils/StrykerTempFolder.ts
- test/unit/StrykerSpec.ts
* Refactor stryker to now stop running where there are no mutants
* Make the main `runMutationTest()` method much clearer to understand by moving all details into seperate methods
* Make use of (parameter context matching)[http://es6-features.org/#ParameterContextMatching]
> fix(stryker): Stop running if there are no mutants

- .travis.yml
Hi Y'all,
Node.js is [releasing quite fast](https://nodejs.org/en/download/releases/) nowadays. It would be cool if you could also test this against the last two versions (especially since 6 has a LTS release).  Since this was a quick implementation, I went ahead an just added the PR instead of discussing this in an issue first. If that's a problem feel free to close the PR anyway.
Some additional remarks:
- What about `node` as a version? this will install the latest stable release.
- I was going to add the lowest LTS versions of node here (`4.20` and `6.9.0`) but since Node.js is now semver updating shouldn't be a problem if users are experiencing a problem. Let me know if you would like to add `4.2.0` and `6.9.0` anyway.
> Add Node.js 6 & 7 to the Travis build matrix

- .travis.yml
HI!
As a quick follow-up of #167 this PR will add `node` to the Travis build matrix to build against the latest stable release of node.js ([according to the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions)). 
Let me know if you need anything changed in this PR.
Cheers!
> Add latest node version to the Travis build matrix

- .bithoundrc
- package.json
- stryker.conf.js
- testResources/config-reader/valid.conf.js
- testResources/module/stryker.conf.js
- testResources/sampleProject/stryker.conf.js
Builds no longer break when we have outdated dependencies. However, the build does break if we have an unused dependency.
> fix(stryker.conf.js) Fix bithound status

- .vscode/launch.json
- README.md
- bin/stryker
- src/ConfigReader.ts
- src/stryker-cli.ts
- test/integration/config-reader/ConfigReaderSpec.ts
- testResources/module/package.json
* Add support for the `run` command as the only command for now.
* Remove `-c` / `--configFile` options, instead use an argument
> feat(cli): Add support for commands

- package.json
- src/Sandbox.ts
- src/isolated-runner/IsolatedRunnerOptions.ts
- src/isolated-runner/IsolatedTestRunnerAdapter.ts
- src/isolated-runner/IsolatedTestRunnerAdapterFactory.ts
- src/isolated-runner/IsolatedTestRunnerAdapterWorker.ts
- src/isolated-runner/MessageProtocol.ts
- test/integration/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
- test/integration/isolated-runner/VerifyWorkingFolderTestRunner.ts
- test/unit/SandboxSpec.ts
- test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
Change the current working directory for all isolated sandboxes. This is needed to remove unwanted side effects during test runs. For example RequireJS wasn't able to find files in combination with karma.
* Add new interface `IsolatedRunnerOptions`, which extends `RunnerOptions` with the addition of `SandboxWorkingFolder`
* Change working directory as soon as the IsoltatedTestRunnerAdapterWorker has loaded the plugins as they can be relative to the parent working directory.
> feat(sandbox): Change cwd in `Sandbox`es

- README.md
- package.json
- src/InputFileResolver.ts
- src/stryker-cli.ts
- test/unit/InputFileResolverSpec.ts
- testResources/sampleProject/stryker.conf.js
Add a way to exclude files. This works respecting the order of the file patterns. Only works when providing patterns as a `string`, not for the `InputFileDescriptor` format.
* Refactor `InputFileResolver`, included a new class `PatternResolver` in order to reuse functionality for both `mutate` and `files`.
* Ignore patterns starting with an `!` as long as they are provided as strings
* Deduplicate files, first occurance wins.
* Document behavior in the readme and add example to cli help text
As discussed in [stryker-api#10](https://github.com/stryker-mutator/stryker-api/pull/10)
> feat(exclude-files): Exclude files with a `!`

- package.json
- test/unit/utils/parserUtilsSpec.ts
* Remove `mocha-sinon` integration layer. We don't use it anymore. Instead we use sinon sandboxes directly.
> refactor(mocha-sinon): Remove integration

- README.md
- src/reporters/ClearTextReporter.ts
- test/unit/reporters/ClearTextReporterSpec.ts
Fixes #196 by limiting the amount of tests that are shown to 3. You can override this using the config file.
> feat(ClearTextReporter): Limit the tests that the ClearTextReporter shows

- .gitignore
- src/InputFileResolver.ts
- src/Sandbox.ts
- src/utils/fileUtils.ts
- test/unit/InputFileResolverSpec.ts
- test/unit/SandboxSpec.ts
- test/unit/utils/fileUtilsSpec.ts
This pull request fixed issue #90
> feat(InputfileResolver): exclude online files from globbing

- src/ConfigReader.ts
- test/integration/config-reader/ConfigReaderSpec.ts
- testResources/config-reader/stryker.conf.js
- testResources/config-reader/valid.conf.js
Our README said we would look for `stryker.conf.js` in the current working directory when you execute `stryker run` without any other arguments, but we didn't support that yet. Now we do!
> feat(ConfigReader): Look for stryker.conf.js in the CWD

- src/ReporterOrchestrator.ts
- src/reporters/ProgressAppendOnlyReporter.ts
- src/reporters/ProgressKeeper.ts
- src/reporters/ProgressReporter.ts
- src/utils/Timer.ts
- test/helpers/producers.ts
- test/unit/ReporterOrchestratorSpec.ts
- test/unit/reporters/ProgressAppendOnlyReporter.ts
- test/unit/reporters/ProgressReporterSpec.ts
* Create a new progress reporter, one which only appends. It prints progress every 10 seconds.
* When the "progress" reporter is not used when the console does not support it.
fixes #212
> feat(append-only-progress): Implement new reporter

- test/unit/ReporterOrchestratorSpec.ts
Test would break when adding the html reporter. Use global state for now, instead of mocking the dependency away.
> test(ReporterOrchestrator): Make test less strict

- .vscode/launch.json
Remove old `--configFile` option from Run stryker example config
> chore(example): Remove `--configFile`

- src/reporters/ClearTextReporter.ts
Assuming this should be "no coverage" instead of "not covered" based on the context around this log message
> fix(typo): change not coverage to no coverage

- testResources/module/package.json
I'll also fix this on the Lerna branch
> fix(install-module): Use TypeScript 2.2 in integration tests

- packages/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.ts
- packages/stryker/test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
> fix(IsolatedTestRunnerAdapter): Don't kill processes using SIGKILL

- package.json
- tasks/link.js
Add the ability of running build steps from child packages. For example, run `npm test` from /packages/stryker. Done this by creating a plugin outside this repo and using it as dev dependency.
> refactor(build): Add ability to run build steps from a child package

- packages/stryker-html-reporter/package.json
- packages/stryker-jasmine/package.json
- packages/stryker-mocha-runner/package.json
Update keywords in package.json of the packages to specify if it is a
test runner, test framework or a reporter. This is useful to dynamically
query in `stryker init` command.
> chore(pkg): Update keywords in package.json

- .travis.yml
Fix travis build by making sure node 5 is NOT used. It has a bug a.t.m. which makes integration tests fail:
https://github.com/npm/npm/issues/16812
> chore(node-8): Fix travis build

- packages/stryker/src/initializer/StrykerInitializer.ts
- packages/stryker/test/unit/initializer/StrykerInitializerSpec.ts
Remove the install of `stryker` itself on `stryker init`. This results in:
```bash
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\nicoj\example\node_modules\.bin\stryker'
```
(at least on windows)
Fixes #316
> fix(intializer): Remove install of `stryker` itself

- packages/grunt-stryker/CHANGELOG.md
- packages/stryker-api/CHANGELOG.md
- packages/stryker-html-reporter/CHANGELOG.md
- packages/stryker-jasmine/CHANGELOG.md
- packages/stryker-karma-runner/CHANGELOG.md
- packages/stryker-mocha-framework/CHANGELOG.md
- packages/stryker/CHANGELOG.md
I've noticed that Lerna did not update our changelogs in a long time. No clue yet why. Here is a manual update.
> chore: Update changelogs

- .travis.yml
- integrationTest/package-lock.json
- integrationTest/package.json
In the integrationTest folder, use [`install-local`](https://www.npmjs.com/package/install-local) to install all stryker dependencies locally, without relying on npm link (which has [some issues](https://github.com/yarnpkg/yarn/issues/1761#issuecomment-259706202)).
> fix(npm5): Make stryker build npm5 compatible

- README.md
- packages/stryker/README.md
I've updated the README's section on Usage to also discuss using the `init` command and I've added a part about the command-line interface.
> docs(README): Add part about the cli

- packages/stryker/src/ConfigReader.ts
Just some simple info logging to solve #332.
The output is now:
```
$ stryker run
[2017-07-14 19:39:23.916] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2017-07-14 19:39:23.919] [FATAL] ConfigReader - File ~/Development/infosupport/opensource/stryker/stryker-cli-test/stryker.conf.js does not exist!
[2017-07-14 19:39:23.919] [FATAL] ConfigReader - { Error: Cannot find module '~/Development/infosupport/opensource/stryker/stryker-cli-test/stryker.conf.js'
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at ConfigReader.loadConfigModule (~/Development/infosupport/opensource/stryker/stryker/packages/stryker/src/ConfigReader.js:38:32)
at …
```
> feat(ConfigReader): Add inform about init

- packages/stryker/stryker.conf.js
- packages/stryker/test/helpers/registerSinonPlugins.ts
- packages/stryker/test/unit/reporters/EventRecorderReporterSpec.ts
When running stryker on stryker, we didn't include the stryker-api module in the test files. This meant that every sandbox shared the stryker-api files with the `IsolatedtestRunnerAdapterWorker` child process. Since we now have a `MochaConfigWriter`, that one is always added to the `ConfigWriterFactory`. It polluted the tests in the sandbox, resulting in an initial test failure.
>  test(own-dogfood): Add stryker-api files in stryker.conf.js

- packages/stryker-html-reporter/.vscode/settings.json
- packages/stryker-html-reporter/package.json
- packages/stryker-karma-runner/test/integration/KarmaTestRunner.it.ts
Make the build [TypeScript 2.5.2](https://github.com/Microsoft/TypeScript/releases/tag/v2.5.2) compatible:
* Make `KarmaTestRunner.ts` compatible with new `Object.keys` signature.
* Remove types of selenium-webdriver. We don't really need them and they are not yet compatible with 2.5
> chore(build): Make build ts 2.5 compatible

- packages/grunt-stryker/tasks/stryker.js
Only running the Stryker grunt task should cause 'stryker' to be required. Also guards against upstream tasks clearing require cache.
> refactor(stryker task): Move stryker require inside stryker task (#362)

- packages/stryker/src/ScoreResultCalculator.ts
- packages/stryker/test/unit/ScoreResultCalculatorSpec.ts
Wrap single file score reports in a base directory. That way, it will be easier for reporters (for example html reporter) to report a base report file, next to single file result files.
Fixes #378
> fix(score-result): Wrap single file reports

- packages/stryker/src/reporters/ProgressAppendOnlyReporter.ts
- packages/stryker/src/reporters/ProgressKeeper.ts
- packages/stryker/src/reporters/ProgressReporter.ts
- packages/stryker/test/unit/reporters/ProgressAppendOnlyReporterSpec.ts
- packages/stryker/test/unit/reporters/ProgressReporterSpec.ts
Simplify the progress reporter to now only show relevant information about the progress: `3/23 tested (1 survived)`
fixes #400
> fix(progress reporter): Simpify reported progress

- packages/stryker/src/ConfigReader.ts
- packages/stryker/test/integration/config-reader/ConfigReaderSpec.ts
Change ConfigReader behavior to always use stryker.conf.js if present. CLI
options override options from the file.
Run does not fail anymore if a CLI option, but no config file is specified.
closes #390
> fix(ConfigReader): Use CLI options with default config file

- packages/stryker/src/Sandbox.ts
- packages/stryker/src/SandboxPool.ts
- packages/stryker/src/process/InitialTestExecutor.ts
- packages/stryker/src/process/MutationTestExecutor.ts
- packages/stryker/test/unit/SandboxPoolSpec.ts
- packages/stryker/test/unit/SandboxSpec.ts
- packages/stryker/test/unit/process/InitialTestExecutorSpec.ts
- packages/stryker/test/unit/process/MutationTestExecutorSpec.ts
* Rename `SandboxCoordinator` -> `SandboxPool`
* Make sure newly created sandboxes are also disposed if the SandboxPool is already disposed
fixes #396
> fix(sandbox): Prevent hanging child processes

- packages/stryker/test/unit/SandboxSpec.ts
We checked if the original code was written to the Sandbox in order to test the reset function. However, the original code is already written to the sandbox during the initialization. So what we really want to test is if the *last* call was the original file.
> test(Sandbox): Check if files are reset at the end of a testrun

- integrationTest/test/karma-jasmine/verify/verify.ts
- integrationTest/test/mocha-mocha/verify/verify.ts
- integrationTest/test/typescript-transpiling/verify/verify.ts
- packages/stryker-html-reporter/src/HtmlReporter.ts
- packages/stryker-html-reporter/src/templates/layout.tsx
- packages/stryker-html-reporter/test/integration/StrykerReportSpec.ts
- packages/stryker-html-reporter/test/integration/singleFileInFolderSpec.ts
- packages/stryker-html-reporter/test/unit/HtmlReporter.spec.ts
Rename `__resources` to `strykerResources` as folders starting with `_` are not served by github by default.
closes #420
> feat(html reporter): Make report gh-pages compatible

- packages/stryker-karma-runner/package.json
- packages/stryker-typescript/package.json
* Add a `initStrykerConfig` section to the stryker-typescript package.json file. 
* Remove `mutate` section from `stryker-karma-runner`. A test runner shouldn't force mutation of certain files.
Closes #454
> fix(init stryker typescript): Add init section

- packages/stryker-typescript/src/TypescriptMutator.ts
- packages/stryker-typescript/src/mutator/ArrowFunctionMutator.ts
- packages/stryker-typescript/test/unit/mutator/ArrowFunctionMutatorSpec.ts
- packages/stryker-typescript/test/unit/mutator/BlockMutatorSpec.ts
The current implementation of BlockMutator doesn't catch anonymous
functions that use the shorthard return value syntax such as:
```
const lengthOf = (s: string) => s.length
```
Closes #456
> feat(typescript-mutator): Implement new ArrowFunctionMutator

- packages/stryker-typescript/src/TypescriptMutator.ts
- packages/stryker-typescript/src/TypescriptTranspiler.ts
- packages/stryker-typescript/src/helpers/tsHelpers.ts
- packages/stryker-typescript/test/helpers/producers.ts
- packages/stryker-typescript/test/unit/TypescriptMutatorSpec.ts
- packages/stryker-typescript/test/unit/helpers/tsHelpersSpec.ts
- packages/stryker-typescript/test/unit/mutator/mutatorAssertions.ts
Use a slightly more low level api to parse typescript files so we can force typescript to set parent nodes. This is useful for creating node mutators, as we can use information about the parent to determine what tho mutate.
> refactor(typescript): Set parent nodes

- packages/stryker-typescript/src/TypescriptMutator.ts
- packages/stryker-typescript/src/mutator/StringLiteralMutator.ts
- packages/stryker-typescript/test/integration/sampleSpec.ts
- packages/stryker-typescript/test/unit/mutator/StringLiteralMutatorSpec.ts
This mutator will empty out string values. Some of them will cause
compilation errors, but others are useful. It ensures error messages and
other such messages are tested.
> feat(typescript-mutation): Add a StringLiteral mutator.

- package.json
- packages/stryker-html-reporter/test/unit/HtmlReporter.spec.ts
- packages/stryker-jasmine/test/unit/index.spec.ts
- packages/stryker-javascript-mutator/test/helpers/initSinon.ts
- packages/stryker-karma-runner/test/unit/KarmaConfigEditorSpec.ts
- packages/stryker-karma-runner/test/unit/KarmaConfigReaderSpec.ts
- packages/stryker-karma-runner/test/unit/KarmaTestRunnerSpec.ts
- packages/stryker-mocha-framework/test/unit/MochaConfigWriterSpec.ts
- packages/stryker-mocha-runner/test/helpers/initSinon.ts
- packages/stryker-typescript/test/helpers/initSinon.ts
- packages/stryker/test/helpers/initSinon.ts
- packages/stryker/test/integration/utils/fileUtilsSpec.ts
- packages/stryker/test/unit/ConfigValidatorSpec.ts
- packages/stryker/test/unit/PluginLoaderSpec.ts
- packages/stryker/test/unit/ReporterOrchestratorSpec.ts
- packages/stryker/test/unit/ScoreResultCalculatorSpec.ts
- packages/stryker/test/unit/TestFrameworkOrchestratorSpec.ts
- packages/stryker/test/unit/initializer/StrykerInitializerSpec.ts
- packages/stryker/test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
- packages/stryker/test/unit/isolated-runner/TimeoutDecoratorSpec.ts
- packages/stryker/test/unit/reporters/ClearTextReporterSpec.ts
- packages/stryker/test/unit/reporters/DotsReporterSpec.ts
- packages/stryker/test/unit/reporters/EventRecorderReporterSpec.ts
- packages/stryker/test/unit/reporters/ProgressAppendOnlyReporterSpec.ts
- packages/stryker/test/unit/reporters/ProgressReporterSpec.ts
- packages/stryker/test/unit/utils/TempFolderSpec.ts
sinon.createSandbox maps to sinon.sandbox.create but all documentation now refers to sinon.createSandbox.
> refactor(sinon): Use createSandbox

- .travis.yml
I noticed that Node v8 is missing from the travis builds since 9 was released
> chore(travis): Build against latest LTS

- packages/stryker-typescript/package.json
- packages/stryker-typescript/src/helpers/tsHelpers.ts
- packages/stryker-typescript/test/unit/TypescriptConfigEditorSpec.ts
- packages/stryker-typescript/test/unit/helpers/tsHelpersSpec.ts
Make stryker-typescript compatible with ts2.4. Note: angular 5 supports ts2.4.
* Update a few tests
* Change the version guard from <=2.5 to <=2.4
* Make sure `npm test` in stryker-typescript runs all tests against version current (2.6) as well as 2.4
> feat(typescript): Backport to TS2.4

- packages/stryker-javascript-mutator/src/JavaScriptMutator.ts
- packages/stryker-javascript-mutator/src/helpers/BabelParser.ts
- packages/stryker-javascript-mutator/test/unit/JavaScriptMutatorSpec.ts
Should fix the issue in: https://github.com/stryker-mutator/stryker/issues/545
Also adds a check for knownextensions ['.js', '.jsx'] so it will not try to mutate other files like html or css.
> Feat(React): Add support for jsx and flow

- package.json
- packages/stryker/package.json
- packages/stryker/src/reporters/ClearTextReporter.ts
- packages/stryker/src/reporters/ClearTextScoreTable.ts
- packages/stryker/src/reporters/DotsReporter.ts
- packages/stryker/test/unit/reporters/ClearTextReporterSpec.ts
- packages/stryker/test/unit/reporters/DotsReporterSpec.ts
The types are now included with the release of chalk so they have been removed from the devDependencies.
>  chore(dependencies): Upgrade to chalk 2.3.0

- packages/stryker-mutator-specification/src/StringLiteralMutatorSpec.ts
- packages/stryker-typescript/src/mutator/StringLiteralMutator.ts
Fixes #563 .
Removes the ability to mutate the `StringLiterals` inside type definitions.
> fix(StringLiteralMutator): Don't mutate string literals in types

- packages/stryker-javascript-mutator/src/JavaScriptMutator.ts
Set the log level in the constructor of the JavaScript mutator plugin.
Fixes #592
> fix(javascript-mutator): Set log level

- packages/stryker-webpack-transpiler/src/WebpackTranspiler.ts
- packages/stryker-webpack-transpiler/test/integration/transpiler.it.ts
- packages/stryker-webpack-transpiler/test/unit/WebpackTranspilerSpec.ts
Throw an error when the webpack transpiler is asked to produce source maps (for now).
> refactor(webpack-transpiler): support new transpiler api

- packages/stryker-typescript/package.json
- packages/stryker-typescript/test/integration/ownDogFoodSpec.ts
The ts 2.4 specific tests in stryker-typescript has some problems running on node 9.5 npm 5.6, removing it from the build.
> test(typescript): remove ts2.4 from build

- packages/stryker-babel-transpiler/src/BabelConfigReader.ts
- packages/stryker-babel-transpiler/test/unit/BabelConfigReaderSpec.ts
Log babel config on debug. Instead of logging only babel config from the `babelConfig` option, now log the resulting config from `babelrcFile` as well.
> fix(babel-transpiler): log babel config on debug

- packages/stryker-javascript-mutator/src/helpers/BabelParser.ts
- packages/stryker-javascript-mutator/test/unit/JavaScriptMutatorSpec.ts
Add these plugins by default:  `'objectRestSpread', 'classProperties', 'asyncGenerators', 'dynamicImport'`
Fixes #612
> feat(javascript-mutator): support more plugins by default

- packages/stryker/package.json
- packages/stryker/src/transpiler/CoverageInstrumenterTranspiler.ts
- packages/stryker/test/unit/transpiler/CoverageInstrumenterTranspilerSpec.ts
The default for `preserveComments` of istanbul-lib-instrumenter was changed (true to false). Make sure it is true so the sourceMappingURL is not overwritten.
Fixes #624
> fix(coverage-analysis): make sure to not erase sourceMappingURL comment

- packages/stryker-api/core.ts
- packages/stryker-api/src/config/Config.ts
- packages/stryker-api/src/core/MutatorDescriptor.ts
- packages/stryker-api/src/core/StrykerOptions.ts
- packages/stryker/README.md
- packages/stryker/src/ConfigValidator.ts
- packages/stryker/src/MutatorFacade.ts
- packages/stryker/src/Stryker.ts
- packages/stryker/src/StrykerCli.ts
- packages/stryker/test/helpers/producers.ts
- packages/stryker/test/unit/ConfigValidatorSpec.ts
- packages/stryker/test/unit/MutatorFacadeSpec.ts
- packages/stryker/test/unit/StrykerSpec.ts
This adds the ability to exclude specific mutation types ('BooleanSubstitution', 'ArrayLiteral', etc.) from being performed during the test run. Can be used via either command-line or config file. Defaults to an empty array, meaning all mutation types are used.
> feat(stryker): Add excludedMutations as a config option (#13)

- .travis.yml
Don't build every LTS version. Build the oldest LTS version and the newest Node version. For now we should also build Node 6 because we use that to release Stryker. When we drop support for Node 4, we will only build `node` and `6`.
This speeds up our travis builds and decreases the chance of random build failures.
> build(node versions): don't build every LTS version

- packages/stryker-api/src/config/Config.ts
- packages/stryker-api/src/core/StrykerOptions.ts
- packages/stryker/README.md
- packages/stryker/src/Sandbox.ts
- packages/stryker/src/utils/fileUtils.ts
- packages/stryker/stryker.conf.js
- packages/stryker/test/helpers/producers.ts
- packages/stryker/test/unit/SandboxSpec.ts
- packages/stryker/test/unit/input/InputFileResolverSpec.ts
- packages/stryker/test/unit/utils/fileUtilsSpec.ts
Add support for `symlinkNodeModules` setting. If true (also the default)
symlink the current node_modules folder in the test runner sandboxes
This will make a test run more "production like".
Also refactor the SandboxSpec so they are more
[DAMP](https://stackoverflow.com/questions/6453235/).
Fixes #672
> feat(Sandbox isolation): symbolic link node_modules in sandboxes

- packages/stryker-javascript-mutator/src/helpers/BabelParser.ts
- packages/stryker-javascript-mutator/src/helpers/ParentNode.ts
- packages/stryker-javascript-mutator/src/mutators/NodeMutator.ts
- packages/stryker-javascript-mutator/src/mutators/StringLiteralMutator.ts
- packages/stryker-javascript-mutator/src/mutators/index.ts
- packages/stryker-javascript-mutator/test/unit/JavaScriptMutatorSpec.ts
- packages/stryker-javascript-mutator/test/unit/mutators/StringLiteralMutatorSpec.ts
Mutates strings into an empty string: `"Hello world!"` -> `""`
Mutates empty strings into non-empty strings: `""` -> `"Stryker was here!"`
Does not mutate `require`, `import`, `"use strict"` or JSX element properties
Fixes #685
> feat(Mutator): Add StringLiteral mutator

- packages/stryker/README.md
Add comma to example config to make it syntactically correct
> docs(stryker-package): add missing comma

- packages/stryker/src/SandboxPool.ts
- packages/stryker/test/unit/SandboxPoolSpec.ts
Remove a race condition where the initalization of a sandbox takes
longer than it takes to run stryker.
Fixes #713
> fix(Sandbox pool): remove race condition

- packages/stryker-webpack-transpiler/src/WebpackTranspiler.ts
- packages/stryker-webpack-transpiler/src/compiler/ConfigLoader.ts
- packages/stryker-webpack-transpiler/test/unit/compiler/ConfigLoaderSpec.ts
The stryker-webpack-transpiler currently expects that the webpack config file exports an object. This PR adds support for config files that exports a function as well - to avoid having to create multiple webpack config files.
> feat(webpack): Add support for config files exporting a function

- .gitignore
- .npmrc
- .travis.yml
- integrationTest/.npmrc
- integrationTest/package-lock.json
- package-lock.json
- package.json
- packages/stryker-api/.npmrc
- packages/stryker-api/package-lock.json
- packages/stryker-api/testResources/module/.npmrc
- packages/stryker-babel-transpiler/package-lock.json
- packages/stryker-html-reporter/package-lock.json
- packages/stryker-jasmine-runner/package-lock.json
- packages/stryker-javascript-mutator/package-lock.json
- packages/stryker-karma-runner/package-lock.json
- packages/stryker-mocha-framework/package-lock.json
- packages/stryker-mocha-runner/package-lock.json
- packages/stryker-typescript/package-lock.json
- packages/stryker-webpack-transpiler/package-lock.json
- packages/stryker/package-lock.json
Lock our dependencies for development. We've been burned too many times.
I've regenerated all package-lock.json files from scratch.
For stryker devs: please use npm 5 or higher.
Fixed #353
> build(lock deps): lock our dependencies for development

- packages/stryker-mutator-specification/src/StringLiteralMutatorSpec.ts
- packages/stryker-typescript/src/mutator/StringLiteralMutator.ts
String literals in a expression statement tend not to have any side effects. So lets assume it's just dead code.
The first string literals in an expression may, given ecma standard rules be converted to prologue directives and have no meaning when being executed.
> fix(String mutator): do not mutate prologue directives

- integrationTest/test/angular-project/package.json
- package-lock.json
- package.json
- packages/stryker-babel-transpiler/package-lock.json
- packages/stryker-html-reporter/package-lock.json
- packages/stryker-html-reporter/package.json
- packages/stryker-karma-runner/package-lock.json
- packages/stryker-mocha-runner/test/integration/MochaFramework.it.ts
- packages/stryker-webpack-transpiler/package-lock.json
- packages/stryker/package-lock.json
We are currently still supporting node version 6
so it makes sense to downgrade the types we
use to version 6.
> Feat(node): Downgrade node types to version 6

- packages/stryker/package-lock.json
- packages/stryker/package.json
- packages/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.ts
- packages/stryker/src/utils/objectUtils.ts
- packages/stryker/test/unit/isolated-runner/IsolatedTestRunnerAdapterSpec.ts
We cannot trust that a test runner process didn't spawn additional processes. For example, angular cli will spawn an additional process to host the type checker (typescript) in. We should kill the entire process tree.
This fixes an edge case where Stryker doesn't shut down and keeps "hanging" after it is reported "done"
> fix(stryker): kill entire test process tree

- packages/stryker-webpack-transpiler/test/unit/fs/InputFileSystemSpec.ts
`innerFSMock` was typed as the more general `AbstractInputFileSystem` but implemented as `createMockInstance(CachedInputFileSystem);`.
Fixes #957.
> Corrected type of mock file input system spec

- CONTRIBUTING.md
"i.e." roughly means "that is" (I think of it as "in essence"); "e.g." roughly means "for example" (I think of it as "example given").
Missing exclamation mark at the end. You've got to have the right level of oomph!
> Fixed a couple of CONTRIBUTING.md typos

- packages/stryker/src/process/MutationTestExecutor.ts
- packages/stryker/test/unit/process/MutationTestExecutorSpec.ts
Add debug logging of run time error messages for all test runners.
Fixes #977
> fix(stryker): log runtime error messages on debug

- packages/stryker/src/isolated-runner/RetryDecorator.ts
- packages/stryker/test/integration/isolated-runner/ResilientTestRunnerFactory.it.ts
- packages/stryker/test/unit/isolated-runner/RetryDecoratorSpec.ts
> fix(RetryDecorator): Don't crash on first failure

- packages/stryker-javascript-mutator/src/mutators/SwitchCaseMutator.ts
- packages/stryker-mutator-specification/src/SwitchCaseMutatorSpec.ts
- packages/stryker-typescript/src/mutator/SwitchCaseMutator.ts
Hotfix for #1156: if a case clause contains no statements, do not mutate it.
---
I think a better fix (technically) would be to always remove the case clause altogether. However this was discounted as part of #1127 due to it producing unclear reporter output - stryker then considers the entire `switch` block mutated, rather than the single `case` clause.
One possible alternative is ensuring the case is never matched, rather than removing the statments:
```
case "A":
case "B":
console.log("Do some actions");
...
// becomes
case "stryker/expression-that-is-never-matched/40ed2198-a801-40fe-8edd-0531783bc069":
case "B":
console.log("Do some actions");
```
This would pick up mutants for:
- the case clause never being matched
- the case clause resulting action not being tested
Downside is, I …
> fix(mutator): Fix empty case statement unkillable mutant

- packages/stryker/src/ScoreResultCalculator.ts
- packages/stryker/test/unit/ScoreResultCalculatorSpec.ts
The filter method used causes a side-effect that creates a corrupt path, I solved this by short circuiting the filter method so it only returns the elements up untill the element that does no longer match.
solves https://github.com/stryker-mutator/stryker/issues/1140
> fix(ScoreResultCalculator): fix faulty filenames in stryker score result

- packages/stryker-jest-runner/src/JestTestRunner.ts
- packages/stryker-jest-runner/test/helpers/testResultProducer.ts
- packages/stryker-jest-runner/test/unit/JestTestRunnerSpec.ts
Implement `TestStatus.Skipped` for pending jest results so Stryker does not fail on the first testrun when tests are marked as `skip`
Resolves #1152
> fix(JestTestRunner): fix stryker error on skipping tests

- packages/stryker-babel-transpiler/README.md
- packages/stryker-babel-transpiler/package.json
We're in the process of upgrading to Babel 7 and have hit an issue with stryker-babel-transpiler. It loads babel-core 6.
This PR adds ^7.0.0-bridge.0 to the babel-core peer range, as recommended by Babel https://github.com/babel/babel-bridge
> Add ^7.0.0-bridge.0 to babel-core range

- packages/stryker/src/reporters/ProgressAppendOnlyReporter.ts
- packages/stryker/src/reporters/ProgressKeeper.ts
- packages/stryker/src/reporters/ProgressReporter.ts
- packages/stryker/test/unit/reporters/ProgressAppendOnlyReporterSpec.ts
- packages/stryker/test/unit/reporters/ProgressReporterSpec.ts
Adds human readable estimates to the progressbar during stryker testing.
resolves #956
> feat(956) human readable estimates (#956)

- packages/stryker-karma-runner/src/starters/angularStarter.ts
- packages/stryker-karma-runner/test/unit/starters/angularStarterSpec.ts
Add support for angular's public API. It is save to merge, the public api was already there since angular 6.0, but never documented. The private API we're now using will be **removed** when https://github.com/angular/angular-cli/pull/12499 is merged.
> feat(karma-runner): Support angular public api

- packages/stryker-util/src/promisify.ts
- tsconfig.json
Ended up having to use ts-ignore on the one issue that came up because it is using 'this' inside an arrow function.
Fixes #1210
> Enable no implicit this in tsconfig #1210

- packages/stryker/src/Stryker.ts
- packages/stryker/src/StrykerCli.ts
- packages/stryker/test/unit/StrykerSpec.ts
> feat(striker-cli): add remark to run again with loglevel trace

- packages/stryker-api/src/mutant/MutatorFactory.ts
- packages/stryker-api/test/unit/mutant/MutantFactorySpec.ts
> refactor(mutant-generator): Change the 'error' message when a mutator plugin cannot be found

- integrationTest/test/mocha-mocha/stryker.conf.js
- packages/stryker-mocha-framework/src/MochaTestFramework.ts
- packages/stryker-mocha-runner/README.md
- packages/stryker-mocha-runner/src/MochaOptionsLoader.ts
- packages/stryker-mocha-runner/src/MochaTestRunner.ts
- packages/stryker-mocha-runner/test/unit/MochaOptionsLoaderSpec.ts
- packages/stryker-mocha-runner/test/unit/MochaTestRunnerSpec.ts
> feat(mocha-runner): improve Mocha support

- packages/stryker-webpack-transpiler/package.json
Remove the mutation test as a `"posttest"` npm step. This will save some time in our CI builds. We should enable mutation testing for each package in a non-ci build, see #1256
> build(webpack-transpiler): Remove mutation test from ci build

- packages/stryker-mocha-runner/README.md
- packages/stryker-mocha-runner/src/MochaOptionsLoader.ts
- packages/stryker-mocha-runner/src/MochaRunnerOptions.ts
- packages/stryker-mocha-runner/src/MochaTestRunner.ts
- packages/stryker-mocha-runner/test/unit/MochaOptionsLoaderSpec.ts
- packages/stryker-mocha-runner/test/unit/MochaTestRunnerSpec.ts
Add support for the --grep option.
**Use case** 
I'm testing a REST service with a database. Testing the write operations makes the tests fail, which leads to false negative with mutation testing.
Example : 
- Test1: GET /something should only contain N elements.
- Test2: POST /something should be accepted.
If Test1 is runned again, it will fail, even with the original code (it contains N+1 elements now).
The alternative would be to reset the database before every test, but it is time consuming and will make mutation testing much longer.
The --grep option in mocha allows to test read-only operations exclusively, so I'm sure that there is no failed test due to a side effects.
> stryker-mocha-runner : Add support for --grep option

- package.json
Fix issue where `Injector<{foo: string, bar: string}>` is not assignable to `Injector<{foo: string}>` by pinning the TS version to 3.2.2. Seems to be broken since latest TS release. Or it works as intended and was a bug in ts 3.2.2, see https://github.com/Microsoft/TypeScript/issues/29590
> build(ts): Pin ts version to 3.2.2

- packages/stryker-jest-runner/src/JestConfigEditor.ts
- packages/stryker-jest-runner/test/unit/JestConfigEditor.spec.ts
BREAKING CHANGE: removes deprecated 'jest.project' config key and project value 'default'. Please use the 'jest.projectType' config key and the 'custom' project value.
> feat(jest project config): Remove deprecated project setting and 'default' project name

- packages/stryker-api/src/core/StrykerOptions.ts
- packages/stryker/src/config/ConfigReader.ts
- packages/stryker/test/integration/config-reader/ConfigReaderSpec.ts
BREAKING CHANGE: Removes the 'timeoutMs' config option. Please use the 'timeoutMS' config option instead.
> feat(timeoutMS): remove deprecated timeoutMs property

- e2e/test/command/stryker.conf.js
- e2e/test/vue-javascript/stryker.conf.js
- packages/stryker-api/src/config/Config.ts
- packages/stryker-api/src/core/StrykerOptions.ts
- packages/stryker/src/config/ConfigReader.ts
- packages/stryker/src/initializer/presets/VueJsPreset.ts
- packages/stryker/test/integration/config-reader/ConfigReaderSpec.ts
BREAKING CHANGE: Removes the 'reporter' config option. Please use the 'reporters' (plural) config option instead.
> feat(reporter config): remove deprecated reporter config option

- packages/stryker/src/input/InputFileResolver.ts
- packages/stryker/test/unit/input/InputFileResolverSpec.ts
BREAKING CHANGE: removed InputFileDescriptor support. Entries of the `files` and `mutate` array should only contain strings, not objects. The `files` array can be removed in most cases as it can be generated using Git.
> feat(InputFileResolver): remove InputFileDescriptor support

- e2e/test/karma-mocha/stryker.conf.js
- e2e/test/webpack-zero-conf-karma/stryker.conf.js
- packages/stryker-karma-runner/src/KarmaTestRunner.ts
- packages/stryker-karma-runner/src/StrykerKarmaSetup.ts
- packages/stryker-karma-runner/test/integration/sample.it.ts
- packages/stryker-karma-runner/test/unit/KarmaTestRunnerSpec.ts
BREAKING CHANGE: removed the `project` config key. Please use `projectType`. Removed the karmaConfig and karmaConfigKey config keys. Please use the `karma: { }` config key.
> feat(karma config): remove karmaConfig, karmaConfigFile and project config keys

- packages/stryker-babel-transpiler/src/BabelConfigReader.ts
- packages/stryker-babel-transpiler/test/unit/BabelConfigReader.spec.ts
BREAKING CHANGE: removed the babelrcFile and babelConfig config keys. Please use the `babel: { }` config key.
> feat(babel config): remove babelrcFile and babelConfig config keys

- packages/stryker-api/src/config/Config.ts
- packages/stryker-api/src/core/StrykerOptions.ts
- packages/stryker/src/config/ConfigValidator.ts
BREAKING CHANGE: removed the port config key. Ports should be automatically selected.
> feat(port): remove port config key

- .gitignore
> chore: add .DS_Store files to gitignore

- packages/jest-runner/src/JestTestRunner.ts
- packages/jest-runner/test/helpers/testResultProducer.ts
- packages/jest-runner/test/unit/JestTestRunner.spec.ts
Stryker currently treats todo tests `it.todo('some description')` as failed tests. Having these in your test suite will result in `There were failed tests in the initial test run`, and the mutation test run fails. This PR fixes this by treating tests marked todo as skipped instead.
- Checking for tests with 'todo' status when test result status is being determined
- Adding unit test to verify that tests with todo status is marked as skipped
> fix(jest-runner): fix stryker error on todo tests

- packages/jest-runner/src/jestOverrideOptions.ts
- packages/jest-runner/test/integration/JestConfigEditor.it.spec.ts
- packages/jest-runner/test/unit/JestConfigEditor.spec.ts
- packages/jest-runner/testResources/exampleProject/package.json
- packages/jest-runner/testResources/exampleProjectWithExplicitJestConfig/jest.config.js
I propose turning of jest notifications by default. Having test notifications turned on in a project can ofc be a great thing but when stryker runs the tests this adds a lot of noise (one notification each time stryker runs the tests against a mutant). 
- Adding `notify: false` to jestOverrideOptions.ts
- Updating tests to verify that this property is overridden
> feat(jest config): set notify to false in JEST_OVERRIDE_OPTIONS

- packages/typescript/src/TypescriptMutator.ts
- packages/typescript/test/unit/TypescriptMutator.spec.ts
Starts on #656. If this is the right approach, I can also send a PR to remove type definition nodes.
> Stopped mutating nodes with a `declare` modifier

- packages/mocha-framework/package.json
- packages/mocha-runner/README.md
- packages/mocha-runner/package.json
- packages/mocha-runner/src/LibWrapper.ts
- packages/mocha-runner/src/MochaConfigEditor.ts
- packages/mocha-runner/src/MochaOptionsLoader.ts
- packages/mocha-runner/src/MochaTestRunner.ts
- packages/mocha-runner/src/utils.ts
- packages/mocha-runner/test/integration/MochaOptionsLoader.it.spec.ts
- packages/mocha-runner/test/integration/SampleProject.it.spec.ts
- packages/mocha-runner/test/unit/MochaOptionsLoader.spec.ts
- packages/mocha-runner/test/unit/MochaTestRunner.spec.ts
- packages/mocha-runner/testResources/mocha-config/.mocharc.js
- packages/mocha-runner/testResources/mocha-config/.mocharc.json
- packages/mocha-runner/testResources/mocha-config/.mocharc.jsonc
- packages/mocha-runner/testResources/mocha-config/.mocharc.yml
- packages/mocha-runner/testResources/mocha-config/package.json
- packages/mocha-runner/tsconfig.src.json
- packages/mocha-runner/tsconfig.test.json
- packages/mocha-runner/typings/mocha.d.ts
Add support for all mocha's configuration formats:
* Arguments specified on command-line
* Configuration file (.mocharc.js, .mocharc.yml, etc.)
1. .mocharc.js
2. .mocharc.yaml
3. .mocharc.yml
4. .mocharc.jsonc
5. .mocharc.json
* mocha property of package.json
* mocha.opts
This works by using mocha 6's [`loadOptions`](https://mochajs.org/api/module-lib_cli_options.html#.loadOptions) function if it is available.
If not (mocha < 6), use old parsing logic.
See https://mochajs.org/#configuring-mocha-nodejs
Closes #1414
> feat(mocha 6): support all config formats

- packages/vue-mutator/src/VueMutator.ts
- packages/vue-mutator/test/unit/VueMutator.spec.ts
If a .vue file does not have a `<script>` tag (such as in the example project of the vue-cli), Stryker will still attempt to mutate it and access the tag. This will cause the following error: 
```
12:34:42 (665) ERROR StrykerCli an error occurred TypeError: Cannot read property 'attrs' of null
at VueMutator.getVueScriptMutatorAndExtension (/workspace/vue-test-proj/node_modules/@stryker-mutator/vue-mutator/src/VueMutator.js:37:27)
at /workspace/vue-test-proj/node_modules/@stryker-mutator/vue-mutator/src/VueMutator.js:19:32
at Array.forEach (<anonymous>)
at VueMutator.mutate (/workspace/vue-test-proj/node_modules/@stryker-mutator/vue-mutator/src/VueMutator.js:16:20)
at MutatorFacade.mutate (/workspace/vue-test-proj/node_modules/@stryker-mutator/core/src/mutants/MutatorFacade.js:13:14)
at …
```
> fix(vue): fix vue mutator throwing an error on vue files without a script tag

- packages/core/package.json
- packages/core/src/initializer/StrykerConfigWriter.ts
- packages/core/test/unit/initializer/StrykerInitializer.spec.ts
After `stryker init` was succesful, run prettier from the command line using `npx prettier --write stryker.conf.js` in order to format the resulting configuration file, rather than having prettier as a dependency directly.
Prettier became pretty expensive, sitting at 1.2 MB.
Fixes #1261
> feat(formatting): remove dependency on prettier

- perf/tasks/run-perf-tests.ts
https://github.com/sindresorhus/execa/blob/master/readme.md#timeout
> If timeout is greater than `0`, the parent will send the signal identified by the `killSignal` property (the default is `SIGTERM`) if the child runs longer than timeout milliseconds.
Let's see if this improves the current CI issue with the performance tests.
Otherwise I'll have to install the complete project with all dependencies when I can use the other laptop (this one overheats too much - which is not great at around 30°C here).
> ci: disable execa timeout to prevent failing perf job

- packages/core/src/child-proxy/ChildProcessProxy.ts
- packages/core/src/utils/StringBuilder.ts
- packages/core/test/unit/child-proxy/ChildProcessProxy.spec.ts
- packages/core/test/unit/utils/StringBuilder.spec.ts
Make sure out `OutOfMemory` detection works as expected. This fixes a race condition in which the detection didn't work correctly, and an unexpected error was assumed. See https://github.com/stryker-mutator/stryker/issues/1634
Fixes #1634
> fix(child process proxy): OutOfMemory detection

- package.json
Builds started failing at #1678 due to pulling in a patch version for sinon-chai (3.2.3) which causes builds to fail due to mismatched chai typings.
> build(deps-dev): Update @types/sinon-chai from ^3.2.0 to 3.2.2

- packages/core/src/input/InputFileResolver.ts
- packages/core/src/utils/TemporaryDirectory.ts
- packages/core/test/unit/input/InputFileResolver.spec.ts
When overriding the tempDir, make sure those files aren't used as input files
> fix(tempDir): don't resolve temp dir as input files

- packages/core/README.md
* fixing fixing typos in core/readme
First improvement for #1667
> docs: fixing typos in core/readme

- packages/api/src/report/MatchedMutant.ts
- packages/core/src/Sandbox.ts
- packages/core/src/TestableMutant.ts
- packages/core/src/mutants/MutantTestMatcher.ts
- packages/core/src/reporters/ProgressKeeper.ts
- packages/core/src/utils/objectUtils.ts
- packages/core/test/unit/Sandbox.spec.ts
- packages/core/test/unit/TestableMutant.spec.ts
- packages/core/test/unit/mutants/MutantTestMatcher.spec.ts
- packages/core/test/unit/reporters/ProgressReporter.spec.ts
- packages/core/test/unit/utils/TemporaryDirectory.spec.ts
- packages/test-helpers/src/factory.ts
- packages/wct-runner/test/helpers/initChai.ts
Don't fill an array with all test references
when all tests need to run for a mutant.
Instead, use the `runAllTests` flag on a mutant.
Might fix #1779
> feat(mutant-matcher): lower memory usage

- packages/core/src/transpiler/coverageHooks.ts
Don't know why, but sometimes the baseline is undefined which crashes the initial run. With the proposed modification I was able to successfully run with perTest coverageAnalysis.
Fixes #1815
> Fix perTest coverageAnalysis

- packages/core/src/reporters/ProgressAppendOnlyReporter.ts
- packages/core/src/reporters/ProgressKeeper.ts
- packages/core/src/reporters/ProgressReporter.ts
- packages/core/test/unit/reporters/ProgressAppendOnlyReporter.spec.ts
- packages/core/test/unit/reporters/ProgressReporter.spec.ts
as a partial solution for #1844 _now updated_:
- show elapsed time in the progress reporters
- change ETC label to `remaining`
- show times _in nicer format with no seconds, see below_ ~~with minutes with up to 2 decimal places, as opposed to seconds~~ (and continue to show hours starting with 60 minutes)
- unit testing of progress time reporting with 3 mutants
- minor test cleanup fixes
I _originally_ tried this with Prettier, with Stryker configured as proposed in brodybits/prettier#16.
Here is some terminal I/O with the default progress reporter _now outdated (see below for updated sample)_:
```sh
$ node --max-old-space-size=100000 ./node_modules/.bin/stryker run
16:25:24 (1853) INFO ConfigReader Using stryker.conf.js in the current working directory.
16:25:25 (1853) INFO …
```
> [rfc] progress display time improvements

- package.json
This fixes a warning when running `npm install`:
~~~~
npm WARN deprecated @types/execa@2.0.0: This is a stub types definition. execa provides its own type definitions, so you do not need this installed.
~~~~
> Remove the unneeded @types/execa devDependency

- packages/core/README.md
In fact, `off` is the default value of `coverageAnalysis` option
> Delete wrong text about that perTest is by default

- packages/api/src/core/StrykerOptions.ts
Change position of `default` label from `perTest` to `off` in comment of `coverageAnalysis` option.
> Change default for coverageAnalysis in comment

- packages/core/testResources/config-reader/deprecated.conf.js
Adding this to the list of artifacts that need to be automatically checked for formatting errors in #1878
> [nit] chore: remove trailing space from deprecated.conf.js

- workspace.code-workspace
`\\` in `path` results in error messages 'Can not resolve workspace folder' in VsCode Explorer Pane after each folder which contains `\\` in setting string.
> Change `\\` to `/` in workspace.code-workspace

- packages/mutator-specification/src/ArrayDeclarationMutatorSpec.ts
- packages/typescript/src/mutator/ArrayDeclarationMutator.ts
> fix mutation of Array constructor call for TypeScript

- packages/javascript-mutator/package.json
- packages/javascript-mutator/src/JavaScriptMutator.ts
- packages/javascript-mutator/src/helpers/NodeGenerator.ts
- packages/javascript-mutator/src/helpers/copy.ts
- packages/javascript-mutator/src/mutators/ArithmeticOperatorMutator.ts
- packages/javascript-mutator/src/mutators/ArrayDeclarationMutator.ts
- packages/javascript-mutator/src/mutators/ArrowFunctionMutator.ts
- packages/javascript-mutator/src/mutators/BlockStatementMutator.ts
- packages/javascript-mutator/src/mutators/BooleanLiteralMutator.ts
- packages/javascript-mutator/src/mutators/ConditionalExpressionMutator.ts
- packages/javascript-mutator/src/mutators/EqualityOperatorMutator.ts
- packages/javascript-mutator/src/mutators/LogicalOperatorMutator.ts
- packages/javascript-mutator/src/mutators/NodeMutator.ts
- packages/javascript-mutator/src/mutators/ObjectLiteralMutator.ts
- packages/javascript-mutator/src/mutators/StringLiteralMutator.ts
- packages/javascript-mutator/src/mutators/UnaryOperatorMutator.ts
- packages/javascript-mutator/src/mutators/UpdateOperatorMutator.ts
- packages/javascript-mutator/src/mutators/index.ts
- packages/javascript-mutator/test/unit/JavaScriptMutator.spec.ts
- packages/javascript-mutator/test/unit/mutators/ArrowFunctionMutator.spec.ts
* JavaScript mutator code improvements
- use raw string mutations *internally* whenever possible
- generate some of the mutations as AST nodes from the Babel types API
- use some ternaries
- remove some intermediate const declarations no longer needed
- remove a couple of internal utility functions no longer needed
* add Arrow Function Mutator for JavaScript (already supported by the existing TypeScript mutator)
* remove `lodash.clonedeep` from dependencies in packages/javascript-mutator/package.json
These improvements should help reduce the amount of consistency between the JavaScript and TypeScript mutators that I raised in #1893.
/cc @kmdrGroch
> JavaScript mutator improvements

- packages/core/src/initializer/presets/ReactPreset.ts
- packages/core/test/unit/initializer/Presets.spec.ts
- packages/jest-runner/README.md
- packages/jest-runner/src/JestConfigEditor.ts
- packages/jest-runner/src/configLoaders/ReactScriptsJestConfigLoader.ts
- packages/jest-runner/src/configLoaders/ReactScriptsTSJestConfigLoader.ts
- packages/jest-runner/test/integration/JestConfigEditor.it.spec.ts
- packages/jest-runner/test/unit/configLoaders/ReactScriptsJestConfigLoader.spec.ts
- packages/jest-runner/test/unit/configLoaders/ReactScriptsTsJestConfigLoader.spec.ts
As reported in issue  #1435, the react preset is only applicable to a react project set up by create-react-app. It causes some confusion whereas the error (unable to locate package react-scripts) isn't that useful either. Therefore, I propose we change the projectType to react-create-app as it resembles the applicability of this preset. 
For backwards compatibility, "react" and "react-ts" can still be used, however, it does log a deprecation warning. 
ps. First PR 🚀
> feat(cli): change react to create-react-app

- packages/api/schema/stryker-core.json
- packages/api/src/config/Config.ts
- packages/api/test/unit/config/Config.spec.ts
- packages/api/testResources/module/useCore.ts
Uploads the entire source code of your app to the dashboard, in the form of a html report, by default because the default `reportType` for the dashboard reporter is now `full`. Switch to `mutationScore` to only update the score.
Fixes #2018
> feat(Dashboard reporter): upload full html report by default

- e2e/package-lock.json
- e2e/package.json
- packages/karma-runner/package.json
- packages/karma-runner/src/starters/stryker-karma.conf.ts
- packages/karma-runner/test/integration/KarmaTestRunner.it.spec.ts
- packages/karma-runner/test/unit/starters/stryker-karma.conf.spec.ts
- packages/karma-runner/testResources/sampleProject/karma.conf.js
BREAKING CHANGE: Removed PhantomJS as the default browser in favor of ChromeHeadless
Fixes #2034
> feat(karma-runner): use ChromeHeadless as the default browser

- e2e/test/karma-jasmine/stryker.conf.js
- e2e/test/karma-mocha/stryker.conf.js
Disable `client.clearContext` for karma e2e tests
Temporary fix for #2049
> test(e2e): improve e2e stability

- .eslintrc.js
Symlinked modules are now seen as `internal` imports (since latest eslint-plugin-import version). Add that to the eslint config.
> chore(eslint): add `internal` group to import/order

- packages/webpack-transpiler/package.json
- packages/webpack-transpiler/src/fs/InputFileSystem.ts
- packages/webpack-transpiler/src/fs/MemoryFS.ts
- packages/webpack-transpiler/src/fs/memory-fs.ts
- packages/webpack-transpiler/src/types.ts
- packages/webpack-transpiler/test/unit/fs/InputFileSystem.spec.ts
- packages/webpack-transpiler/typings/enhanced-resolve.d.ts
- workspace.code-workspace
Add support for the `cache-loader` plugin by migrating from `memory-fs` to `memfs`.
> fix(webpack-transpiler): add support for cache-loader

- packages/core/src/initializer/StrykerConfigWriter.ts
Schema reference of generated config file should point to local schema file.
> fix(init): use correct schema reference

- packages/karma-runner/src/karma-plugins/TestHooksMiddleware.ts
- packages/karma-runner/test/unit/karma-plugins/TestHooksMiddleware.spec.ts
- packages/util/src/stringUtils.ts
- packages/util/test/unit/stringUtils.spec.ts
When a test name contains a `/`, correctly escape it. Stryker blows up in your face without it.
> fix(karma-runner): mocha filtering with `/`

- e2e/test/vue-cli-typescript-mocha/stryker.conf.json
- e2e/test/vue-cli-typescript-mocha/verify/verify.ts
- packages/typescript-checker/src/fs/hybrid-file-system.ts
- packages/typescript-checker/test/unit/fs/hybrid-file-system.spec.ts
Fix for `inner error: TypeError: Cannot read property 'modifiedTime' of undefined` error.
> fix(typescript-checker): support empty files

- packages/core/src/reporters/MutationTestReportHelper.ts
- packages/core/test/unit/reporters/MutationTestReportHelper.spec.ts
Report `onAllMutantsTested` before `onMutationTestReportReady`
> fix(reporter): report event order

- e2e/test/typescript-transpiling/package.json
- e2e/test/typescript-transpiling/src/Errors.ts
- e2e/test/typescript-transpiling/test/Errors.spec.ts
- e2e/test/typescript-transpiling/verify/verify.ts
- packages/instrumenter/src/mutators/block-statement-mutator.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/mutators/block-statement-mutator.spec.ts
- packages/instrumenter/testResources/instrumenter/super-call.ts
- packages/instrumenter/testResources/instrumenter/super-call.ts.out.snap
Don't mutate constructor bodies with a super call in combination with parameter properties.
Fixes #2314
> fix(mutator): issue with block statement mutator

- e2e/tasks/run-e2e-tests.ts
- e2e/test/command/stryker.conf.json
- e2e/test/command/verify/verify.ts
- packages/api/src/core/instrument.ts
- packages/core/src/test-runner/CommandTestRunner.ts
- packages/core/src/test-runner/index.ts
- packages/core/test/integration/command-test-runner/CommandTestRunner.it.spec.ts
- packages/core/test/unit/test-runner/CommandTestRunner.spec.ts
- packages/core/testResources/command-runner/mutant.js
- packages/core/testResources/command-runner/package.json
- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/integration/transformers.it.spec.js.snap
- packages/instrumenter/testResources/instrumenter/app.component.ts.out.snap
- packages/instrumenter/testResources/instrumenter/html-sample.html.out.snap
- packages/instrumenter/testResources/instrumenter/js-sample.js.out.snap
- packages/instrumenter/testResources/instrumenter/lit-html-sample.ts.out.snap
- packages/instrumenter/testResources/instrumenter/super-call.ts.out.snap
- packages/instrumenter/testResources/instrumenter/ts-sample.ts.out.snap
- packages/instrumenter/testResources/instrumenter/vue-sample.vue.out.snap
- packages/test-helpers/src/assertions.ts
Add support for the command test runner with mutation switching.
_NOTE: Support for the command test runner is "best effort"! It might not work for your test runner of choice_
The switching of mutants is done by providing the `__STRYKER_ACTIVE_MUTANT__` environment variable when executing the command. The `@stryker-mutator/instrumenter` now adds a check for this environment variable in each source file. This only works if the command you configure allows for this environment variable to flow through to the test environment.
In other words: this should work for node test runners like [node-tap](https://node-tap.org/) and mocha but not for test runners that spin up their own test environment, like jest or karma.
Note that for mocha, karma, and jest, you're better of using their respective …
> feat(command): Support command test runner with mutation switching

- e2e/tasks/run-e2e-tests.ts
- e2e/test/jest-react-ts/verify/verify.ts
- e2e/test/jest-react/stryker.conf.js
- e2e/test/jest-react/verify/verify.ts
- e2e/test/mocha-ts-node/package.json
- e2e/test/vue-cli-typescript-mocha/verify/verify.ts
- packages/instrumenter/src/mutators/string-literal-mutator.ts
- packages/instrumenter/src/transformers/babel-transformer.ts
- packages/instrumenter/test/unit/mutators/string-literal-mutator.spec.ts
Don't mutate string literals in object property keys. An example:
```js
// don't mutate these!
const { "aria-label": label } = props;
const foo = { ["aria-label"]: label };
// However, still mutate strings in property values
const bar = { baz: 'qux' } // mutated to { baz: '' }
```
> fix(instrumenter): don't mutate string literals in object properties

- packages/jest-runner/schema/jest-runner-options.json
- packages/jest-runner/src/configLoaders/index.ts
- packages/jest-runner/test/integration/JestTestRunner.it.spec.ts
- packages/jest-runner/test/unit/configLoaders/configLoaderFactory.spec.ts
Remove deprecated project types.
* `react` --> `create-react-app`
* `react-ts` --> `create-react-app-ts`
Fixes #2021
BREAKING CHANGE: Project types `react` and `react-ts` have been removed. Please use `create-react-app` and `create-react-app-ts` respectively
> feat(jest-runner): remove deprecated project types

- packages/api/schema/stryker-core.json
- packages/core/README.md
- packages/core/package.json
- packages/core/src/process/2-MutantInstrumenterExecutor.ts
- packages/core/src/sandbox/create-preprocessor.ts
- packages/core/src/sandbox/file-preprocessor.ts
- packages/core/src/sandbox/index.ts
- packages/core/src/sandbox/multi-preprocessor.ts
- packages/core/src/sandbox/sandbox-file-header-preprocessor.ts
- packages/core/src/sandbox/sandbox-tsconfig-preprocessor.ts
- packages/core/src/sandbox/sandbox.ts
- packages/core/src/utils/fileUtils.ts
- packages/core/test/integration/sandbox/create-preprocessor.it.spec.ts
- packages/core/test/unit/process/2-MutantInstrumenterExecutor.spec.ts
- packages/core/test/unit/sandbox/multi-preprocessor.spec.ts
- packages/core/test/unit/sandbox/sandbox-file-header-preprocessor.spec.ts
- packages/core/test/unit/sandbox/sandbox-tsconfig-rewriter.it.spec.ts
- packages/core/test/unit/sandbox/sandbox.spec.ts
- packages/test-helpers/src/assertions.ts
- workspace.code-workspace
Add the ability to override the file headers inside a sandbox. This allows users to opt-out of the default header, as well as add custom headers.
You can configure it like this:
```json
{
"sandboxFileHeaders": {
"**/*.ts": "// Hello world\n"
}
}
```
The key here is a [glob expression](https://globster.xyz/), where the value points to the header to be used for matching files.
Fixes #2357
> feat(core): add ability to override file headers

- e2e/test/mocha-old-version/package-lock.json
- e2e/test/mocha-old-version/package.json
- e2e/test/mocha-old-version/src/add.js
- e2e/test/mocha-old-version/stryker.conf.json
- e2e/test/mocha-old-version/test/unit/add.spec.js
- e2e/test/mocha-old-version/verify/verify.ts
- packages/mocha-runner/src/LibWrapper.ts
- packages/mocha-runner/src/MochaOptionsLoader.ts
- packages/mocha-runner/test/unit/MochaOptionsLoader.spec.ts
BREAKING CHANGE: Mocha@<6 is deprecated and support for it will be removed in Stryker v5
Fixes #2370
> feat(mocha): deprecate mocha < v6

- packages/instrumenter/src/mutant-placers/conditional-expression-mutant-placer.ts
- packages/instrumenter/test/unit/mutant-placers/conditional-expression-mutant-placer.spec.ts
- packages/instrumenter/testResources/instrumenter/vue-sample.vue.out.snap
Do a best-effort attempt to minimize side effects from instrumentation by maintaining the `fn.name` property when placing mutants in code.
Instrument these:
```ts
const foo = function () { }
const bar = () => {}
const Baz = class { }
const foo = { bar: function () { } }
```
Like this:
```ts
const foo = true? function foo () { }: ...;
const bar = true? (() => { const bar = () =>{}; return bar } {})() : ...;
const Baz = true? class Baz { } : ...;
const foo = true? function bar() {}
```
Fixes #2362
> fix(instrumenter): support anonymous function names

- e2e/test/mocha-javascript/package.json
- e2e/test/mocha-javascript/src/🐱‍👓ninja.cat.js
- e2e/test/mocha-javascript/test/unit/ninjaCat.spec.js
- e2e/test/mocha-javascript/verify/verify.ts
- packages/core/src/input/InputFileResolver.ts
- packages/core/test/unit/input/InputFileResolver.spec.ts
- packages/test-helpers/src/assertions.ts
Support emojis and other encoded characters in file names when using `git ls-files`.
Fixes #2418
> fix(input files): support emojis in file names

- e2e/test/jasmine-ts-node/stryker.conf.json
- e2e/test/jest-react-enyme-ts/stryker.conf.json
- e2e/test/mocha-ts-node/stryker.conf.json
- e2e/test/typescript-transpiling/stryker.conf.json
- e2e/test/vue-cli-javascript-jest/stryker.conf.json
- e2e/test/vue-cli-typescript-mocha/stryker.conf.json
- e2e/test/vue-javascript/stryker.conf.json
- packages/api/schema/stryker-core.json
- packages/core/test/helpers/setupMocha.ts
- packages/core/test/integration/input/InputFileResolver.it.spec.ts
Change the default patterns for which files should be mutated to:
```json
{ 
"mutate": [
"{src,lib}/**/!(*.+(s|S)pec|*.+(t|T)est).+(cjs|mjs|js|ts|jsx|tsx|html|vue)", 
"!{src,lib}/**/__tests__/**/*.+(cjs|mjs|js|ts|jsx|tsx|html|vue)"
]
}
```
Basically means any JS or friend file in the `lib` or `src` directory that isn't obviously a test file.
Fixes #2384
> feat(mutate): a more sane default for `mutate`

- e2e/test/mocha-javascript/verify/verify.ts
- e2e/test/reporters-e2e/.mocharc.jsonc
- e2e/test/reporters-e2e/package-lock.json
- e2e/test/reporters-e2e/package.json
- e2e/test/reporters-e2e/src/Add.js
- e2e/test/reporters-e2e/src/Circle.js
- e2e/test/reporters-e2e/stryker.conf.json
- e2e/test/reporters-e2e/test/helpers/testSetup.js
- e2e/test/reporters-e2e/test/unit/AddSpec.js
- e2e/test/reporters-e2e/test/unit/CircleSpec.js
- e2e/test/reporters-e2e/verify/verify.ts
- packages/core/src/reporters/MutationTestReportHelper.ts
- packages/core/test/unit/reporters/MutationTestReportHelper.spec.ts
Correctly report the average tests/mutant metric in the clear-text reporter
> fix(reporters): correctly report avg tests/mutants

- .github/workflows/mutation-testing.yml
- packages/test-helpers/src/TestInjector.ts
Fix a memory leak in Strykers' own tests. Reuse of the `typed-inject@3` `Injector` caused essentially every object to ever be injected to be reachable and thus not garbage collectible.
We're now recreating a new Injector for each test.
Fixes #2456
> test(helpers): fix a memory leak

- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts
- packages/instrumenter/testResources/instrumenter/issues/urls-in-strings.js
- packages/instrumenter/testResources/instrumenter/type-definitions.ts
- packages/instrumenter/testResources/instrumenter/type-definitions.ts.out.snap
Don't instrument TS `as` expressions as this can result in invalid code.
Fixes #2465
> fix(instrumenter): skip `as` expressions

- .github/workflows/mutation-testing.yml
- packages/instrumenter/src/mutators/block-statement-mutator.ts
- packages/instrumenter/test/unit/mutators/block-statement-mutator.spec.ts
Don't mutate constructor block statements when the class contains initialized class properties. For example:
```ts
class Foo extends Baz {
bar = 'bar';
constructor() {  // Don't mutate this block!
super();
}
}
```
If you mutate the constructor block above, and TypeScript transpiles the code, it will call `this.bar` before the `super()` is initiated. Resulting in a runtime error.
Fixes #2474
> fix(instrumenter): don't mutate constructor blocks with initialized class properties

- e2e/test/mocha-javascript/stryker.conf.json
- e2e/test/mocha-javascript/test/unit/Circle.spec.js
- e2e/test/mocha-javascript/verify/verify.ts
- packages/core/src/mutants/findMutantTestCoverage.ts
- packages/core/test/unit/mutants/findMutantTestCoverage.spec.ts
Allow for a coverage per test result for a non-existing test. This can happen when you add a `this.skip` inside a `it`. In that case, `beforeEach` still executes and can add test coverage.
We now ignore simply ignore this and log a debug message.
Fixes #2485
> fix(core): allow skipped tests when matching mutants

- packages/core/src/Stryker.ts
- packages/core/src/concurrent/pool.ts
- packages/core/test/unit/Stryker.spec.ts
- packages/instrumenter/src/mutant-placers/index.ts
- packages/instrumenter/src/transformers/babel-transformer.ts
- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/helpers/syntax-test-helpers.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/mutant-placers/index.spec.ts
- packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts
- packages/instrumenter/testResources/instrumenter/flow-typed.js
- packages/instrumenter/testResources/instrumenter/flow-typed.js.out.snap
- packages/instrumenter/testResources/instrumenter/ts-declarations.ts
- packages/instrumenter/testResources/instrumenter/ts-declarations.ts.out.snap
> feat(instrumenter): harden the instrumenter

- e2e/test/coverage-analysis/package.json
- e2e/test/coverage-analysis/spec/concat.spec.js
- e2e/test/coverage-analysis/spec/math.spec.js
- e2e/test/coverage-analysis/spec/support/jasmine.json
- e2e/test/coverage-analysis/src/concat.js
- e2e/test/coverage-analysis/src/math.js
- e2e/test/coverage-analysis/verify/coverage-analysis-reporter.js
- e2e/test/coverage-analysis/verify/verify.ts
Add e2e test for coverage analysis `off`, `all` and `perTest`.
Fixes #2486
> test(e2e): add e2e test for coverage analysis

- packages/core/src/input/InputFileResolver.ts
- packages/core/src/sandbox/sandbox.ts
- packages/core/src/utils/fileUtils.ts
- packages/core/test/integration/input/InputFileResolver.it.spec.ts
- packages/core/test/unit/input/InputFileResolver.spec.ts
- packages/core/test/unit/sandbox/sandbox.spec.ts
Fixes "too many open files" issue by limiting the number of concurrent file IO to 256
Fixes #1227
> fix(core): fix "too many open files"

- .github/ISSUE_TEMPLATE/bug_report.md
- packages/core/src/config/ConfigReader.ts
- packages/core/test/integration/config-reader/ConfigReader.it.spec.ts
- packages/core/testResources/config-reader/deprecated.conf.js
- packages/core/testResources/config-reader/deprecatedFunction.conf.js
- packages/core/testResources/config-reader/js/stryker.conf.js
- packages/core/testResources/config-reader/json-and-js/stryker.conf.js
- packages/jasmine-runner/.mocharc.jsonc
Export a function from you're config file is deprecated. Please export an object, or use a json file.
Fixes: #2429
> fix(config): deprecate function based config

- packages/instrumenter/src/transformers/babel-transformer.ts
- packages/instrumenter/src/transformers/mutant-collector.ts
- packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts
- packages/instrumenter/test/unit/transformers/mutant-collector.spec.ts
- packages/instrumenter/testResources/instrumenter/flow-typed.js.out.snap
- packages/instrumenter/testResources/instrumenter/ts-declarations.ts.out.snap
- packages/instrumenter/testResources/instrumenter/type-definitions.ts.out.snap
Only add the JS header for files that have mutants. For example: don't add it in `*.d.ts` files.
Fixes #2502
> fix(instrumenter): only add header when there are mutants

- packages/core/src/process/3-DryRunExecutor.ts
- packages/core/src/utils/Timer.ts
- packages/core/test/unit/process/3-DryRunExecutor.spec.ts
- packages/core/test/unit/utils/Timer.spec.ts
> feat(Initial test run): start timing the test run when logging that the run is starting

- .gitmodules
- packages/util/src/deepMerge.ts
- packages/util/test/unit/deepMerge.spec.ts
> fix(mutate config): don't warn about files not existing at the default mutate location

- e2e/test/mocha-javascript/src/Add.js
- packages/instrumenter/src/disable-type-checks.ts
- packages/instrumenter/test/integration/disable-type-checks.it.spec.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/disable-type-checks.spec.ts
- packages/instrumenter/testResources/disable-type-checks/app.component.ts.out.snap
- packages/instrumenter/testResources/instrumenter/shebang.js
- packages/instrumenter/testResources/instrumenter/shebang.js.out.snap
Support shebang (i.e. `#!/usr/bin/env node`) in javascript files.
Fixes #2398
> fix(shebang): support shebang in in files

- packages/core/README.md
Fixes stryker-mutator/stryker#2520
> docs(readme): add missing commandRunner option

- packages/instrumenter/src/mutant-placers/index.ts
- packages/instrumenter/src/mutant-placers/switch-case-mutant-placer.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/mutant-placers/switch-case-mutant-placer.spec.ts
- packages/instrumenter/testResources/instrumenter/switch-case.js
- packages/instrumenter/testResources/instrumenter/switch-case.js.out.snap
Add a `MutantPlacer` for `SwitchCase` nodes. It places the mutants in the `consequence` part of the switch case. This can dramatically improve the performance of instrumenting large switch-case statements.
This:
```js
switch(foo){
case 'bar':
console.log('bar');
break;
case 'baz':
console.log('baz');
break;
}
```
Is now instrumented as:
```js
switch (foo) {
case stryMutAct_9fa48(1) ? \\"\\" : (stryCov_9fa48(1), 'bar'):
if (stryMutAct_9fa48(0)) {} else {
stryCov_9fa48(0);
console.log(stryMutAct_9fa48(2) ? \\"\\" : (stryCov_9fa48(2), 'bar'));
break;
}
case stryMutAct_9fa48(4) ? \\"\\" : (stryCov_9fa48(4), 'baz'):
if (stryMutAct_9fa48(3)) {} else {
stryCov_9fa48(3);
console.log(stryMutAct_9fa48(5) ? \\"\\" : (stryCov_9fa48(5), 'baz'));
break;
}
}
```
While previously the entire …
> fix(instrumenter): switch case mutant placer

- packages/core/src/initializer/StrykerConfigWriter.ts
- packages/core/src/initializer/StrykerInitializer.ts
- packages/core/src/initializer/presets/AngularPreset.ts
- packages/core/src/initializer/presets/PresetConfiguration.ts
- packages/core/src/initializer/presets/ReactPreset.ts
- packages/core/src/initializer/presets/VueJsPreset.ts
- packages/core/test/unit/initializer/Presets.spec.ts
- packages/core/test/unit/initializer/StrykerInitializer.spec.ts
Update the VueJS, react and angular presets for the 4.0 release.
Closes #2521
> fix(presets): update `init` templates for 4.0 release

- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts
- packages/instrumenter/testResources/instrumenter/ts-declarations.ts
- packages/instrumenter/testResources/instrumenter/ts-declarations.ts.out.snap
Don't mutate `TSTypeParameterInstantiation` like `React.useState<true>()`
Fixes #2527
> fix(instrumenter): don't mutate generics

- packages/instrumenter/src/mutators/string-literal-mutator.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/mutators/string-literal-mutator.spec.ts
- packages/instrumenter/testResources/instrumenter/string-mutations.ts
- packages/instrumenter/testResources/instrumenter/string-mutations.ts.out.snap
Don't mutate class property keys that are written as a string literal.
```ts
class Foo { 
'bar-baz': 4 // don't mutate
}
```
Fixes #2543
> fix(string-literal-mutator): don't mutate class property keys

- packages/api/schema/stryker-core.json
- packages/core/README.md
- packages/core/src/concurrent/concurrency-token-provider.ts
- packages/core/test/unit/concurrent/concurrency-token-provider.spec.ts
Sets the default `--concurrency` to CPU count when the number of available CPU's <= 4.
Also updates the docs (apparently, `--concurrency` was missing from the readme).
Fixes #2542
> fix(concurrency): better default for low CPU count

- packages/core/package.json
Remove the `strip-comments` dependency, it was used in the betas but is no longer used.
> chore(deps): remove unused dependency

- packages/instrumenter/src/parsers/index.ts
> Add missing case for .jsx files in parser

- .github/workflows/ci.yml
We keep the strategy of running the pipeline on the lowest active LTS and highest active LTS.
> chore(ci): run pipeline on node 14 (instead of 12).

- packages/core/package.json
- packages/core/src/reporters/html/templates/index.html
The parent html page of the mutation-test-report-app listens to the theme-changed event, and changes it's background color according to the new theme.
> feat(report): Change theme together with mutation-test-report-app

- e2e/test/jest-with-ts/package.json
- e2e/test/jest-with-ts/src/components/hello-component.test.ts
- e2e/test/jest-with-ts/src/components/hello-component.ts
- e2e/test/jest-with-ts/stryker.conf.json
- e2e/test/jest-with-ts/tsconfig.json
- e2e/test/jest-with-ts/verify/verify.ts
- packages/instrumenter/src/disable-type-checks.ts
- packages/instrumenter/test/unit/disable-type-checks.spec.ts
Keep the `@jest-environment` directive atop test files.
Fixes #2569
> fix(disable-checking): allow jest environment

- packages/api/schema/stryker-core.json
- packages/core/README.md
- packages/core/src/index.ts
- packages/core/src/process/3-dry-run-executor.ts
- packages/core/src/stryker-cli.ts
- packages/core/test/unit/config/options-validator.spec.ts
- packages/core/test/unit/process/3-dry-run-executor.spec.ts
- packages/core/test/unit/stryker-cli.spec.ts
Fixes #2302 (partly) by introducing a new optional timeout parameter for the initial test run.
> Inital timeout parameter

- packages/api/schema/stryker-core.json
- packages/core/README.md
- packages/core/src/index.ts
- packages/core/src/reporters/html/html-reporter.ts
- packages/core/src/reporters/index.ts
- packages/core/src/reporters/json-reporter.ts
- packages/core/src/reporters/reporter-util.ts
- packages/core/test/unit/reporters/html/html-reporter.spec.ts
- packages/core/test/unit/reporters/json-reporter.spec.ts
Fixes #1814. The implementation is relatively simple and copies most of the code from the html reporter. Probably this can be refactored at some point so that there is less duplicated logic. But it works for now.
> Add a json reporter

- packages/karma-runner/src/starters/angular-starter.ts
- packages/karma-runner/src/starters/karma-starter.ts
- packages/karma-runner/src/starters/stryker-karma.conf.ts
- packages/karma-runner/src/utils.ts
- packages/karma-runner/test/integration/read-config.it.spec.ts
- packages/karma-runner/test/unit/starters/angular-starter.spec.ts
- packages/karma-runner/test/unit/starters/stryker-karma.conf.spec.ts
- packages/util/.vscode/launch.json
- packages/util/package.json
- packages/util/src/index.ts
- packages/util/src/require-resolve.ts
- packages/util/test/integration/require-resolve.it.spec.ts
- packages/util/testResources/.gitignore
- packages/util/testResources/require-resolve/baz/node_modules/bar/index.js
- packages/util/testResources/require-resolve/foo/node_modules/bar/index.js
- packages/util/testResources/require-resolve/node_modules/bar/index.js
Require `karma` or `@angular/cli` from the current working directory (cwd), instead of from `@stryker-mutator/karma-runner/src/util.js` (where the old `requireModule` function lived).
> feat(karma-runner): resolve local karma version

- packages/jest-runner/src/utils/jest-wrapper.ts
Require `jest` from the current working directory, instead of from the `@stryker-mutator/jest-runner` itself.
> feat(jest-runner): resolve local jest version

- packages/core/src/stryker-cli.ts
Please use 'trace' to get the same functionality.
Fixes #2613
> fix(CLI help): remove non-existant logLevel 'all'

- .eslintrc.js
- packages/api/.eslintrc
- packages/core/.eslintrc
- packages/grunt-stryker/.eslintrc
- packages/instrumenter/.eslintrc
- packages/jasmine-runner/.eslintrc
- packages/jest-runner/.eslintrc
- packages/karma-runner/.eslintrc
- packages/mocha-runner/.eslintrc
- packages/test-helpers/.eslintrc
- packages/typescript-checker/.eslintrc
- packages/util/.eslintrc
Remove eslint config per package. The vscode-eslint plugin now supports mono-repo config.
> chore(eslint): remove per-package config

- e2e/test/angular-project/verify/verify.ts
- e2e/test/jest-react/verify/verify.ts
- packages/instrumenter/src/mutators/arithmetic-operator-mutator.ts
- packages/instrumenter/test/unit/mutators/arithmatic-operator-mutator.spec.ts
As discussed in #2646, this is a shallow "Best-effort" approach to not mutating obvious string concatenations
> fix(instrumentor): Do not run the arithmetic operator mutator on obvious string concatenations

- packages/jasmine-runner/src/jasmine-test-runner.ts
- packages/jasmine-runner/test/integration/jasmine-runner.it.spec.ts
- packages/jasmine-runner/test/integration/memory-leak.worker.ts
- packages/jasmine-runner/test/unit/jasmine-test-runner.spec.ts
- packages/jasmine-runner/testResources/big-project/lib/big-text.js
- packages/jasmine-runner/typings/jasmine-types.d.ts
- packages/karma-runner/package.json
- packages/mocha-runner/src/mocha-test-runner.ts
- packages/mocha-runner/test/integration/mocha-file-resolving.it.spec.ts
- packages/mocha-runner/test/integration/mocha-options-loader.it.spec.ts
- packages/mocha-runner/test/integration/project-with-root-hooks.it.spec.ts
- packages/mocha-runner/test/unit/mocha-test-runner.spec.ts
- packages/mocha-runner/testResources/big-project/src/big-text.js
- packages/util/.vscode/launch.json
- packages/util/src/directory-require-cache.ts
- packages/util/test/unit/directory-require-cache.spec.ts
- packages/util/test/unit/string-utils.spec.ts
Allow modules to be cleared while it is loaded from any parent module. This allows us to handle clearing files from any parent, regardless of whether it moved around.
> refactor(cache): clear modules from any parent module

- packages/core/src/child-proxy/child-process-proxy.ts
- packages/core/test/integration/child-proxy/child-process-proxy.it.spec.ts
- packages/core/test/unit/child-proxy/child-process-proxy.spec.ts
Aside from "JavaScript heap out of memory", also assume that "FatalProcessOutOfMemory" is an out of memory error. Sometimes "JavaScript heap out of memory" isn't logged, but FatalProcessOutOfMemory is.
> fix(child-process): improve out-of-memory recognition

- packages/core/src/concurrent/pool.ts
- packages/core/src/process/3-dry-run-executor.ts
- packages/core/src/process/4-mutation-test-executor.ts
- packages/core/test/helpers/producers.ts
- packages/core/test/integration/child-proxy/child-process-proxy.it.spec.ts
- packages/core/test/unit/concurrent/pool.spec.ts
- packages/core/test/unit/process/2-mutant-instrumenter-executor.spec.ts
- packages/core/test/unit/process/3-dry-run-executor.spec.ts
- packages/core/test/unit/process/4-mutation-test-executor.spec.ts
Implement resource like pattern. Schedule work to be done on the pool with `pool.schedule(input$, task)`.
The pool itself is responsible to make sure only one task is executed on one worker at any one time. The pool is also responsible to recycle the worker after it is done with a task.
> refactor(pool): implement resource-like pattern

- packages/instrumenter/package.json
- packages/instrumenter/src/mutators/index.ts
- packages/instrumenter/src/mutators/regex-mutator.ts
- packages/instrumenter/src/tsconfig.json
- packages/instrumenter/src/typings/weapon-regex.ts
- packages/instrumenter/test/unit/mutators/regex-mutator.spec.ts
This PR adds support for smart regex mutations to Stryker. 👽
Some examples:
```ts
/\d{4}\s[a-Z]{2}/;
// Mutates to:
/\d\s[a-Z]{2}/; // => Quantifier removal
/\D{4}\s[a-Z]{2}/; // => Predefined Character Class Negation
/\d{4}\S[a-Z]{2}/; // => Predefined Character Class Negation
/\d{4}\s[a-Z]/; // => Quantifier removal
/\d{4}\s[^a-Z]{2}/; // => Character Class Negation
```
Stryker will identify regex literals: `/\d{4}\s[a-Z]{2}/` as well as clear regex string literals in a `RegExp` constructor: `new RegExp('\\d{4}\\s[a-Z]{2}')`. After that it uses the awesome [Weapon-regeX](https://github.com/stryker-mutator/weapon-regex/) library to generate mutants based on the regex pattern. These mutants are then placed inside the code with regular mutation switching practises.
Weapon regex supports …
> feat(regex-mutator): smart regex mutations

- packages/instrumenter/src/mutant-placers/index.ts
- packages/instrumenter/src/mutators/string-literal-mutator.ts
- packages/instrumenter/test/unit/mutant-placers/index.spec.ts
- packages/instrumenter/test/unit/mutators/string-literal-mutator.spec.ts
- packages/instrumenter/testResources/instrumenter/vue-sample.vue
- packages/instrumenter/testResources/instrumenter/vue-sample.vue.out.snap
Don't mutate object method names that are disguised as string literals. For example:
```ts
const foo = {
"bar.baz"(qux) { }
}
```
Fixes #2695
> fix(mutator): don't mutate string literal object methods

- docs/configuration.md
Hi there :wave: 
First of all, thank you all for maintaining Stryker, it's an amazing tool! :pray: 
I just noticed that the `coverageAnalysis` section in the documentation was not up-to-date, regarding the latest jest-runner coverageAnalysis features (`perTest` and `all`). 
That's what this small PR is here for!
Cheers!
> docs(configuration): update coverageAnalysis section according to the latest jest-runner features

- packages/mocha-runner/src/stryker-mocha-reporter.ts
- packages/mocha-runner/test/integration/regession.it.spec.ts
- packages/mocha-runner/testResources/regression/issue-2720/failing-after-each.js
- packages/mocha-runner/testResources/regression/issue-2720/failing-before-each.js
Report the test name when a beforeEach or afterEach hook fails.
Fixes #2720
> fix(reporting): report test name when a hook fails

- e2e/package-lock.json
- e2e/package.json
- e2e/test/flow-test-project/.babelrc
- e2e/test/flow-test-project/package-lock.json
- e2e/test/flow-test-project/package.json
- e2e/test/flow-test-project/src/square.js
- e2e/test/flow-test-project/src/square.spec.js
- e2e/test/flow-test-project/stryker.conf.json
- e2e/test/flow-test-project/verify/.babelrc
- e2e/test/flow-test-project/verify/verify.ts
- packages/instrumenter/src/transformers/babel-transformer.ts
- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/integration/transformers.it.spec.ts.snap
- packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts
- packages/instrumenter/test/unit/util/syntax-helpers.spec.ts
This means that the stryker mutator hooks are no longer just
prepended to the beginning of file. Instead we also add the comments
which means things like flow should behave correctly
Fixes #2704
> fix(babel-transformer): respect top of the file comments/pragma

- packages/instrumenter/testResources/instrumenter/specific-mutants.ts.out.snap
- packages/instrumenter/testResources/instrumenter/specific-no-mutants.ts.out.snap
- tsconfig.settings.json
JS will now be es2019 complient, instead of es2017. Minimal node version should be node 12.
BREACKING CHANGE: Support for node 10 is dropped.
> feat(es): convert to es2019

- packages/core/src/utils/file-utils.ts
- packages/core/test/unit/utils/file-utils.spec.ts
First create directory if it not already existing _before_ creating the symlink to `node_modules` inside the sandbox directory.
> fix(sandbox): make directory if not exists before symlinking

- package.json
- packages/api/package.json
- packages/core/package.json
- packages/instrumenter/package.json
- packages/jasmine-runner/package.json
- packages/jest-runner/package.json
- packages/karma-runner/package.json
- packages/mocha-runner/package.json
- packages/typescript-checker/package.json
BREAKING CHANGE: Node 10 is no longer supported. Please use Node 12 or higher.
> feat(node): Drop support for node 10

- packages/instrumenter/src/mutators/logical-operator-mutator.ts
- packages/instrumenter/test/unit/mutators/logical-operator-mutator.spec.ts
Allow the logical operator mutator to mutate [nullish coalescing operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) to a logical [AND (&&) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND):
```diff
-foo ?? bar
+foo && bar
```
> feat(mutator): mutate nullish coalescing operator

- packages/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter.ts
Use the local jest version in the Jest<25 adapter. Fixes potential `Error: TypeError: Cannot read property 'runCLI' of undefined` errors.
> fix(jest-runner): use local jest version when jest@<25

- e2e/test/jest-react-ts/package-lock.json
- e2e/test/jest-react-ts/package.json
- e2e/test/jest-react-ts/src/App.test.js
- e2e/test/jest-react-ts/src/App/TodoList/Item/index.test.tsx
- e2e/test/jest-react-ts/src/App/TodoList/index.test.tsx
- e2e/test/jest-react-ts/src/App/style.ts
- e2e/test/jest-react-ts/src/index.tsx
- e2e/test/jest-react-ts/stryker.conf.json
- e2e/test/jest-react-ts/tsconfig.json
- e2e/test/jest-react-ts/verify/verify.ts
- packages/jest-runner/package.json
- packages/jest-runner/src/jest-plugins/jest-environment-generic.ts
- packages/jest-runner/src/jest-plugins/mixin-jest-environment.ts
- packages/jest-runner/src/jest-plugins/with-coverage-analysis.ts
- packages/jest-runner/src/messaging.ts
- packages/jest-runner/test/helpers/producers.ts
- packages/jest-runner/test/unit/jest-plugins/jest-environment-generic-jest-environment.ts
- packages/jest-runner/test/unit/jest-plugins/jest-environment-generic.spec.ts
- packages/jest-runner/test/unit/jest-plugins/mixin-jest-environment.spec.ts
- packages/jest-runner/test/unit/jest-test-runner.spec.ts
Support *any* configured `testEnvironment` in Jest configuration for coverage analysis, by dynamically mixing in the `StrykerTestEnvironment` class. This adds 'native support' for coverage analysis in react projects.
Fixes #2789
> feat(jest-runner): dynamically override "testEnvironment"

- docs/guides/vuejs.md
Hi !
I have fixed the stryker.conf.json of `docs/guides/vuejs.md`.
why?: that's invalid json format.
thx.
> fix invalid json format of stryker.conf.json

- docs/mocha-runner.md
- packages/mocha-runner/src/mocha-test-runner.ts
- packages/mocha-runner/test/unit/mocha-test-runner.spec.ts
Provide a clear error message when users configure `mochaOptions.require` to include `"esm"`. You should provide it as a node argument instead.
```diff
{
"$schema": "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
"testRunner": "mocha",
"mochaOptions": {
-   "require": ["esm"]
},
+ "testRunnerNodeArgs": ["--require", "esm"]
}
```
Fixes #3014
> fix(mocha-runner): clear error when require esm

- .github/workflows/ci.yml
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/stryker-cli.ts
- packages/core/test/unit/stryker-cli.spec.ts
StrykerJS supports Node 12.17 and higher. This change adds a clear error message when you run it with a lower node version
Fixes #3007
> fix(node 12): clear error message for node <12.17

- packages/api/schema/stryker-core.json
- packages/api/src/test-runner/mutant-run-result.ts
- packages/api/src/test-runner/run-result-helpers.ts
- packages/api/test/unit/test_runner/run-result-helpers.spec.ts
- packages/core/src/reporters/mutation-test-report-helper.ts
- packages/core/test/integration/command-test-runner/command-test-runner.it.spec.ts
- packages/core/test/unit/config/options-validator.spec.ts
- packages/core/test/unit/reporters/mutation-test-report-helper.spec.ts
- packages/core/test/unit/test-runner/command-test-runner.spec.ts
- packages/jest-runner/schema/jest-runner-options.json
- packages/jest-runner/src/jest-test-runner.ts
- packages/jest-runner/test/helpers/producers.ts
- packages/jest-runner/test/integration/coverage-analysis.it.spec.ts
- packages/jest-runner/test/integration/file-under-test-outside-roots.it.spec.ts
- packages/jest-runner/test/integration/jest-test-runner.it.spec.ts
- packages/jest-runner/test/unit/jest-test-runner.spec.ts
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/.gitignore
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/package.json
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/src/Add.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/src/Multiply.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/src/__tests__/AddSpec.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks-instrumented/src/__tests__/MultiplySpec.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks/package.json
- packages/jest-runner/testResources/jasmine2-node-no-mocks/src/Add.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks/src/Multiply.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks/src/__tests__/AddSpec.js
- packages/jest-runner/testResources/jasmine2-node-no-mocks/src/__tests__/MultiplySpec.js
- packages/test-helpers/src/factory.ts
- tasks/instrument-test-resources.js
As discussed in #2996 and #3012 this PR enables the user to set a `disableBail` option to collect all tests killing a mutant.
Notes on the implementation:
1. Initially only implemented for jest. The rest of the test runners should continue to work without changes
1. I deleted the `enableBail` option from `jest-runner-options.json`. I figured since this new `disableBail` option at the striker level it made no sense to keep it. It might be necessary to do the same for all test helpers
1. We only track the first error message of the first failing test. 
To be done:
> WIP - Create the disableBail option.

- docs/disable-mutants.md
* Fixes the relative link to the documentation for equivalent mutants
* Fixes an example of equivalent mutants that aren't really equivelant and doesn't match the screenshot below
> docs(disable-mutants): fix typo

- packages/core/src/reporters/progress-reporter.ts
- packages/core/test/unit/reporters/progress-reporter.spec.ts
> fix(ProgressReporter): don't render when there are no valid mutants to render

- docs/disable-mutants.md
The line above says "restore the EqualityOperator for 1 line:", so I guess the "next-line" keyword should be used.
> Fix typo in disable-mutants docs

- packages/instrumenter/test/unit/mutant-placers/expression-mutant-placer.spec.ts
- packages/instrumenter/test/unit/mutant-placers/statement-mutant-placer.spec.ts
- packages/instrumenter/test/unit/mutant-placers/switch-case-mutant-placer.spec.ts
Hard-code the placer names in test `describe` functions, so the string mutator cannot impact the test names.
Fixes #3168
> test(placers): hard code placer names in test descriptions

- e2e/package-lock.json
- e2e/package.json
- e2e/test/jest-with-ts/stryker.conf.json
- e2e/test/jest-with-ts/verify/verify.ts
- packages/typescript-checker/.vscode/launch.json
- packages/typescript-checker/src/fs/hybrid-file-system.ts
- packages/typescript-checker/test/unit/fs/hybrid-file-system.spec.ts
TypeScript 4.4 also watches package.json files in node_modules for changes. I guess this is done to be able to reload the types when a node_module gets updated.
However, the typescript-checker wasn't expecting those `watchFile` calls to come in. The checker was defensive programmed, meaning an error is thrown when something happens that it doesn't expect.
This ended up being a simple fix. Simply ignoring `watchFile` of files that are not loaded seems to do the trick.
Fixes #3176
> fix(typescript-checker): support TS 4.4

- docs/configuration.md
Just a minor update to be extra clear to users:
We never bail in Jest but we mimic based on disableBail
> specify behavior of jest when disableBail

- packages/api/src/test-runner/run-options.ts
- packages/core/src/process/3-dry-run-executor.ts
- packages/core/test/unit/process/3-dry-run-executor.spec.ts
- packages/jest-runner/src/jest-test-adapters/jest-greater-than-25-adapter.ts
- packages/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter.ts
- packages/jest-runner/src/jest-test-adapters/jest-test-adapter.ts
- packages/jest-runner/src/jest-test-runner.ts
- packages/jest-runner/test/unit/jest-test-adapters/jest-greater-than-25-adapter.spec.ts
- packages/jest-runner/test/unit/jest-test-runner.spec.ts
> feat: run initial test using jest findRelatedTests

- docs/configuration.md
If you want to target a specific file (or files) for mutation, such as those that are staged in Git, the `--mutate` option works better than `--ignorePatterns`.
> docs: --mutate as an alternative to --files

- packages/instrumenter/src/util/syntax-helpers.ts
- packages/instrumenter/test/unit/util/syntax-helpers.spec.ts
Don't mutate generic declarations, like `{color} {position}` in
```ts
function foo<T extends `{color} {position}`>() {
}
```
Fixes #3253
> fix(instrumenter): don't mutate TS generics

- packages/core/src/sandbox/ts-config-preprocessor.ts
- packages/core/test/unit/sandbox/ts-config-preprocessor.it.spec.ts
Rewrite `include` patterns in tsconfig files that fall outside the sandbox.
For example:
```json
{
"include": ["./**/*", "../../node_modules/self-service-server/lib/main/shared/@types/**/*.d.ts"],
}
```
Becomes:
```json
{
"include": ["./**/*", "../../../../node_modules/self-service-server/lib/main/shared/@types/**/*.d.ts"],
}
```
Same is true for `files` and `exclude`.
Fixes #3281
> fix(tsconfig): rewrite "include" patterns

- packages/typescript-checker/src/tsconfig-helpers.ts
- packages/typescript-checker/test/unit/typescript-helpers.spec.ts
Even user enabled is config in their `tsconfig.json` file, typescript compiler will throw exception below anyway. So it better to just disabled in adjustment config.
```
TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
```
> fix(config): `declarationMap` should disabled as well

- packages/jasmine-runner/package.json
Clearly document that jasmine 4 is not yet supported in the `peerDependencies`
> fix(jasmine): correct peer dependency for jasmine

- .github/dependabot.yml
Disable dependabot in e2e directory. Unfortunately, this means no dependabot anymore in root package.json 😢
See https://github.com/dependabot/dependabot-core/issues/4364#issuecomment-1038194085
> chore(dependabot): disable dependabot in e2e dir

- docs/config-file.md
- packages/core/src/config/config-file-formats.ts
- packages/core/src/config/config-reader.ts
- packages/core/src/initializer/stryker-config-writer.ts
- packages/core/test/integration/config-reader/config-reader.it.spec.ts
- packages/core/test/unit/config/config-reader.spec.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
- packages/core/testResources/config-reader/hidden/.stryker.conf.js
Accept hidden files (starting with a dot) for configuration. Configuration files are often hidden files (such as _.mocharc.js_ or _.eslintrc.js_).
With this pull request, the `stryker.conf.(json|js|mjs|cjs)` and `.stryker.conf.(json|js|mjs|cjs)` files are searched by default.
> feat: Accept hidden config file.

- packages/karma-runner/src/karma-test-runner.ts
- packages/karma-runner/test/unit/karma-test-runner.spec.ts
Don't reject the init promise when disposing during initialization in the karma runner.
Fixes #3486
> fix(karma-runner): allow dispose during init

- docs/mocha-runner.md
Fix link _[mocha's internal file loading mechanism](https://mochajs.org/api/module-lib_cli_options.html#.loadOptions)_ (in [Mocha Runner](https://stryker-mutator.io/docs/stryker-js/mocha-runner#configuring)).
> docs(mocha-runner): fix link to loadOptions

- packages/core/src/di/plugin-loader.ts
- packages/core/test/unit/di/plugin-loader.spec.ts
Don't warn the user when it is running StrykerJS without plugins:
```
WARN PluginLoader Expression "@stryker-mutator/*" not resulted in plugins to load.
```
Fixes #3497
> fix(plugin loader): no warn when not using plugins

- packages/instrumenter/.vscode/launch.json
- packages/instrumenter/src/mutators/arithmetic-operator-mutator.ts
- packages/instrumenter/src/mutators/array-declaration-mutator.ts
- packages/instrumenter/src/mutators/assignment-operator-mutator.ts
- packages/instrumenter/src/mutators/boolean-literal-mutator.ts
- packages/instrumenter/src/mutators/conditional-expression-mutator.ts
- packages/instrumenter/src/mutators/logical-operator-mutator.ts
- packages/instrumenter/src/mutators/unary-operator-mutator.ts
- packages/instrumenter/src/mutators/update-operator-mutator.ts
- packages/instrumenter/test/helpers/expect-mutation.ts
- packages/instrumenter/test/integration/transformers.it.spec.ts.snap
Verifies that mutators don't accidentally reinsert original parts of the AST inside mutated parts. This has been a problem in the past, so probably best to avoid it using an assertion helper.
Fixes #3510
> test(mutators): verify original node immutability

- packages/core/src/sandbox/sandbox.ts
- packages/core/test/unit/sandbox/sandbox.spec.ts
Log missing `node_modules` for symlinking as 'debug' rather than 'warning'.
When running Stryker in a child directory of a mono-repo, which doesn't have a `node_modules` directory, Stryker would log a warning. This is far too aggressive.
> feat(warn): no longer warn about non-existing node_modules

- e2e/package-lock.json
- e2e/package.json
- package-lock.json
- package.json
Stop linking parent binaries in `node_modules/.bin` directories of packages, as this is no longer needed. Recent releases of NPM already add the parent `node_module/.bin` directory to the PATH env variable when running with `npm run`
> chore(npm run): Stop linking parent bin

- packages/jest-runner/src/jest-plugins/cjs/mixin-jest-environment.ts
- packages/jest-runner/test/unit/jest-plugins/mixin-jest-environment.spec.ts
Allow `mixinJestEnvironment` to be used under normal unit testing without Stryker.
This way was already documented, but broke in v6 release:
https://stryker-mutator.io/docs/stryker-js/jest-runner/#coverage-reporting
Fixes #3584
> fix(jest): allow mixin jest env for unit testing

- .eslintrc.cjs
- e2e/test/mocha-old-version/verify/verify.js
- packages/jasmine-runner/test/unit/jasmine-test-runner.spec.ts
- packages/karma-runner/test/unit/karma-test-runner.spec.ts
- tasks/instrument-test-resources.js
- workspace.code-workspace
Enable the no-floating-promises rule and fix all linting errors.
Also configure eslint plugin for vscode to show all errors as warnings.
> refactor(eslint): enable 'no-floating-promises' rule

- e2e/helpers.js
- e2e/test/disable-bail/verify/verify.js
- e2e/test/ignore-project/verify/verify.js
- e2e/test/jest-node/verify/verify.js
- e2e/test/reporters-e2e/verify/verify.js
- e2e/test/reporters-e2e/verify/verify.js.snap
- packages/core/src/reporters/mutation-test-report-helper.ts
- packages/core/test/unit/reporters/mutation-test-report-helper.spec.ts
- packages/util/src/string-utils.ts
- packages/util/test/unit/string-utils.spec.ts
Make all file paths relative in the JSON report. This is needed to make the JSON portable between servers/machines when using `--incremental` mode.
> fix(reporting): make all file paths relative in report

- package.json
- packages/api/.npmrc
- packages/core/.npmrc
- packages/cucumber-runner/.npmrc
- packages/grunt-stryker/.npmrc
- packages/instrumenter/.npmrc
- packages/jasmine-runner/.npmrc
- packages/jest-runner/.npmrc
- packages/karma-runner/.npmrc
- packages/mocha-runner/.npmrc
- packages/test-helpers/.npmrc
- packages/typescript-checker/.npmrc
- packages/util/.npmrc
Configure legacy peer dependencies using `.npmrc` files instead of a lerna cli argument. I hope that this way: renovate bot will also be aware if this flag.
> chore(npmrc): configure legacy peer deps using npmrc

- docs/configuration.md
at: https://stryker-mutator.io/docs/stryker-js/configuration/#dashboard-dashboardoptions
the "config file" example has a typo:
**dasboard** instead of **dashboard**
> typo in docs: config file example for dashboard

- packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts
- packages/instrumenter/test/integration/instrumenter.it.spec.ts
- packages/instrumenter/test/unit/mutant-placers/expression-mutant-placer.spec.ts
- packages/instrumenter/testResources/instrumenter/mutant-placing.ts
- packages/instrumenter/testResources/instrumenter/mutant-placing.ts.out.snap
Allow the conditional expression mutant placer to place mutants inside computed member expressions.
For example, allow mutants to be placed in `foo.bar()` here:
```js
baz[foo.bar()]
```
Fixes #3702
Fixes #3647
> fix(mutant placing): computed member expressions

- packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts
- packages/instrumenter/test/unit/mutant-placers/expression-mutant-placer.spec.ts
- packages/instrumenter/testResources/instrumenter/optional-chains.ts
- packages/instrumenter/testResources/instrumenter/optional-chains.ts.out.snap
Fix a regression in mutant placing inside an optional chain.
For example: `bar?.baz[0]`
```diff
- (stryMutAct_9fa48("9") ? bar.baz : (stryCov_9fa48("9"), bar?.baz)[0];"
+ stryMutAct_9fa48("9") ? bar.baz[0] : (stryCov_9fa48("9"), bar?.baz[0]);"
```
Fixes #3717
> fix(mutant-placing): regression in optional chain

- docs/getting-started.md
Hi, thanks for Stryker Mutator, really cool project! 🙌
The readme has a link to the Configuration docs page, so to avoid the indirection (and 2 clicks instead of 1), the link could go directly to the Configuration docs page (as is done in this PR)
> Avoid indirection

- packages/jest-runner/src/config-loaders/custom-jest-config-loader.ts
- packages/jest-runner/src/config-loaders/index.ts
- packages/jest-runner/src/config-loaders/react-scripts-jest-config-loader.ts
- packages/jest-runner/src/jest-plugins/cjs/import-jest-environment.ts
- packages/jest-runner/src/jest-plugins/cjs/messaging.ts
- packages/jest-runner/src/jest-plugins/with-coverage-analysis.ts
- packages/jest-runner/src/jest-test-adapters/jest-greater-than-25-adapter.ts
- packages/jest-runner/src/jest-test-adapters/jest-less-than-25-adapter.ts
- packages/jest-runner/src/jest-test-adapters/jest-test-adapter-factory.ts
- packages/jest-runner/src/jest-test-runner.ts
- packages/jest-runner/src/plugin-di.ts
- packages/jest-runner/src/plugin-tokens.ts
- packages/jest-runner/src/utils/jest-wrapper.ts
- packages/jest-runner/test/helpers/producers.ts
- packages/jest-runner/test/unit/config-loaders/config-loader-factory.spec.ts
- packages/jest-runner/test/unit/config-loaders/custom-jest-config-loader.spec.ts
- packages/jest-runner/test/unit/config-loaders/react-scripts-jest-config-loader.spec.ts
- packages/jest-runner/test/unit/jest-test-adapters/jest-greater-than-25-adapter.spec.ts
- packages/jest-runner/test/unit/jest-test-adapters/jest-test-adapter-factory.spec.ts
- packages/jest-runner/test/unit/jest-test-runner.spec.ts
- packages/jest-runner/test/unit/utils/jest-wrapper.spec.ts
Use the jest instance relative to `react-scripts` when the `projectType` is `"create-react-app"`, instead of simply loading jest from the CWD. This allows users to install a newer version of `jest` right next to `react-scripts` to be used for other tasks.
Fixes #3783
> fix(jest): support multiple jest installations

- CONTRIBUTING.md
- docs/troubleshooting.md
- packages/api/schema/stryker-core.json
- packages/core/src/initializer/stryker-config-writer.ts
- packages/core/src/initializer/stryker-initializer.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
stryker init command now has the option to use pnpm instead of npm as package manager.
Resolves #3448 and closes #3221 (duplicates)
> feat(core): add support for pnpm as package manager

- packages/jest-runner/src/jest-test-runner.ts
- packages/jest-runner/test/unit/jest-test-runner.spec.ts
Set the NODE_ENV environment parameter before calling the jest cli to ensure features like transition animations in UI components are disabled during testing.
Fixes #3580
> Set NODE_ENV parameter in jest test runner

- packages/core/src/initializer/npm-client.ts
- packages/core/src/initializer/stryker-config-writer.ts
- packages/core/src/initializer/stryker-initializer.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
**Add feature #1212**
Initial setup providing fetching the URL from the response and displaying it in the comment property of the `stryker.conf.json`.
> Add documentation to generated stryker.conf.js

- packages/core/test/unit/fs/project-file.spec.ts
The previous test implementation was a copy of the sandbox tetst. This points the test to the correct method.
> tests: correct filesystem test for writeToBackup to call correct method

- packages/api/.mocharc.cjs
- packages/api/.mocharc.jsonc
- packages/core/.mocharc.cjs
- packages/core/.mocharc.jsonc
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
- packages/cucumber-runner/.mocharc.cjs
- packages/cucumber-runner/.mocharc.jsonc
- packages/instrumenter/.mocharc.cjs
- packages/jasmine-runner/.mocharc.cjs
- packages/jasmine-runner/.mocharc.jsonc
- packages/jest-runner/.mocharc.cjs
- packages/jest-runner/.mocharc.jsonc
- packages/karma-runner/.mocharc.cjs
- packages/karma-runner/.mocharc.jsonc
- packages/mocha-runner/.mocharc.cjs
- packages/mocha-runner/.mocharc.jsonc
- packages/typescript-checker/.mocharc.cjs
- packages/typescript-checker/.mocharc.jsonc
- packages/util/.mocharc.cjs
- packages/util/.mocharc.jsonc
Closes #3818 
Add the `--forbid-only` argument to mocha when running tests on the build server to give a more concrete warning when you've accidentally pused a `it.only()` test.
Before:
https://github.com/stryker-mutator/stryker-js/actions/runs/3347971096/jobs/5546534847#step:5:2780
After:
https://github.com/Giovds/stryker-js/actions/runs/3355540113/jobs/5559880282#step:5:918
> feat(cicd): Add --forbid-only in mocha config

- CONTRIBUTING.md
The previous sentence had a double 'the', which made the sentence harder to read.
> docs: update contributing file with better scope explanation

- packages/core/src/initializer/stryker-config-writer.ts
- packages/core/src/initializer/stryker-initializer.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
Closes #3829
The URL to the test runner docs is not correctly resolved by certain editors because it contains a `"` closing the string. To avoid running in this issue the URL is away from the end of the string.
> Rephrase test runner docs for better clickable url

- packages/core/src/mutants/incremental-differ.ts
- packages/core/test/unit/mutants/incremental-differ.spec.ts
Fix a bug in the diffing algorithm where, running in `--incremental` mode, the test file would always be marked as 'changed' when it contained tests generated using a function, which was the last in the file.
For example:
```js
import { add } from "../add.js";
test.each`
x    | y    | expected
${1} | ${1} | ${2}
${1} | ${2} | ${3}
${2} | ${2} | ${4}
`("add($x, $y) = $expected", ({ x, y, expected }) => {
expect(add(x, y)).toBe(expected);
});
```
Closes #3909
> fix(diff): last test generation

- packages/instrumenter/src/mutators/string-literal-mutator.ts
Replace babel's deprecated `isModuleDeclaration` call with `isImportOrExportDeclaration`.
Fixes #4022
> fix(instrumenter): replace deprecated method call

- docs/typescript-checker.md
Misdescription of the TypeScript Checker configuration
> typescriptChecker typo

- packages/api/src/report/dry-run-completed-event.ts
- packages/core/src/mutants/mutant-test-planner.ts
- packages/core/src/process/3-dry-run-executor.ts
- packages/core/src/reporters/progress-keeper.ts
- packages/core/test/unit/process/3-dry-run-executor.spec.ts
- packages/core/test/unit/reporters/progress-keeper.spec.ts
- packages/core/test/unit/reporters/progress-reporter.spec.ts
- packages/test-helpers/src/factory.ts
Improve Estimated Time to Completion (ETC) prediction by considering test runner capabilities. When a test runner can reload the test environment, it will no longer assume the test runner overhead cost is needed for static mutants.
Fixes #4018
> fix(progress reporter): improve ETC prediction

- packages/core/src/checker/checker-facade.ts
- packages/core/src/checker/checker-resource.ts
- packages/core/src/fs/project-file.ts
- packages/core/src/process/2-mutant-instrumenter-executor.ts
- packages/core/src/reporters/progress-append-only-reporter.ts
- packages/core/src/reporters/progress-keeper.ts
- packages/core/src/reporters/progress-reporter.ts
- packages/core/test/helpers/file-system-test-double.ts
- packages/core/test/integration/process/1-prepare-executor.it.spec.ts
- packages/core/test/unit/child-proxy/hello-class.ts
- packages/core/test/unit/fs/project-file.spec.ts
- packages/core/test/unit/reporters/progress-keeper.spec.ts
- packages/core/test/unit/sandbox/sandbox.spec.ts
- packages/instrumenter/src/transformers/transformer.ts
- packages/jest-runner/src/plugin-di.ts
- packages/jest-runner/src/utils/jest-wrapper.ts
- packages/typescript-checker/src/grouping/create-groups.ts
- packages/typescript-checker/src/grouping/ts-file-node.ts
- packages/typescript-checker/test/unit/grouping/ts-file-node.spec.ts
Refactor type imports to use the public `exports`. I.e.
```diff
-import { MutantRunPlan } from '@stryker-mutator/api/src/core';
+import { MutantRunPlan } from '@stryker-mutator/api/core';
```
> refactor(type imports): use public exports

- docs/parallel-workers.md
(Revival of #4061, I messed up with GitHub codespaces)
Fixes https://github.com/stryker-mutator/stryker-js/issues/4034
> :memo: Add precision about file conflicts within project

- .github/workflows/ci.yml
- package-lock.json
- package.json
- packages/api/package-lock.json
- packages/api/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/test/unit/stryker-cli.spec.ts
- packages/cucumber-runner/package-lock.json
- packages/cucumber-runner/package.json
- packages/grunt-stryker/package-lock.json
- packages/grunt-stryker/package.json
- packages/instrumenter/package-lock.json
- packages/instrumenter/package.json
- packages/jasmine-runner/package-lock.json
- packages/jasmine-runner/package.json
- packages/jest-runner/package-lock.json
- packages/jest-runner/package.json
- packages/karma-runner/package-lock.json
- packages/karma-runner/package.json
- packages/mocha-runner/package-lock.json
- packages/mocha-runner/package.json
- packages/typescript-checker/package-lock.json
- packages/typescript-checker/package.json
On april 30th support for [node 14 is end-of-life](https://github.com/nodejs/release#release-schedule). Because of this support will be dropped so we can support new features like the upcomming tap runner.
> Drop node 14 support

- packages/tap-runner/src/setup/env.cts
- packages/tap-runner/src/setup/hook.cts
- packages/tap-runner/src/tap-helper.ts
- packages/tap-runner/src/tap-parser-factory.ts
- packages/tap-runner/src/tap-test-runner.ts
- packages/tap-runner/test/setup.ts
- packages/tap-runner/test/unit/tap-runner.spec.ts
A (possible) fix for the issue described in [#4122.](https://github.com/stryker-mutator/stryker-js/issues/4122). The tap-runner now waits for the spawned process to exit before returning the results.
I think this will fix the problem we encounter in de ci pipeline, but I could not recreate the problem locally.
> Fix(tap-runner): wait for spawned process to exit

- packages/instrumenter/testResources/instrumenter/optional-chains.ts
- packages/instrumenter/testResources/instrumenter/optional-chains.ts.out.snap
Add a missing test for optional chaining inside a computed property.
Fixes #3475
> test(instrumenter): add test for optional chaining

- packages/cucumber-runner/test/integration/cucumber-runner.it.spec.ts
- packages/test-helpers/src/assertions.ts
Allow out-of-order test results in `expectTestResults` by sorting expectations and actuals by `testId`.
> refactor(assertions): sort tests in `expectTestResults`

- e2e/test/incremental/package.json
- e2e/test/incremental/spec/concat.tap.js
- e2e/test/incremental/spec/concat.tap.js.changed
- e2e/test/incremental/spec/concat.tap.js.original
- e2e/test/incremental/spec/math.tap.js
- e2e/test/incremental/spec/math.tap.js.changed
- e2e/test/incremental/spec/math.tap.js.original
- e2e/test/incremental/verify/verify.js
- e2e/test/incremental/verify/verify.js.snap
- e2e/test/incremental/vitest.config.js
- packages/vitest-runner/src/file-communicator.ts
- packages/vitest-runner/src/vitest-helpers.ts
- packages/vitest-runner/test/integration/vitest-test-runner.it.spec.ts
- packages/vitest-runner/test/unit/vitest-helpers.spec.ts
Add `vitest` and `tap` runner to the `incremental` e2e test set. 
Also change the vitest-runner to report relative file names as testId:
- ✅ Smaller test ids
- ✅ Easier snapshot testing
Closes #4110
Closes #4109
> test(incremental): add vitest and tap to e2e

- .gitignore
- packages/vitest-runner/src/file-communicator.ts
- packages/vitest-runner/src/vitest-test-runner.ts
- packages/vitest-runner/test/unit/file-communication.spec.ts
Base the communication directory of the vitest runner on the current working directory (cwd) rather than the `node_modules/@stryker-mutator/vitest-runner` directory.
Fixes #4214
> fix(vitest): use cwd for communication dir

- packages/api/src/report/reporter.ts
- packages/core/src/reporters/broadcast-reporter.ts
- packages/core/src/reporters/dots-reporter.ts
- packages/core/src/reporters/event-recorder-reporter.ts
- packages/core/src/reporters/mutation-test-report-helper.ts
- packages/core/src/reporters/progress-append-only-reporter.ts
- packages/core/test/unit/reporters/broadcast-reporter.spec.ts
- packages/core/test/unit/reporters/dots-reporter.spec.ts
- packages/core/test/unit/reporters/mutation-test-report-helper.spec.ts
- packages/test-helpers/src/factory.ts
BREAKING CHANGE: The event `onAllMutantsTested` has been removed. Plugin creators should use `onMutationTestReportReady` instead.
Fixes #4156
> feat(reporter-api): remove `onAllMutantsTested`

- e2e/package-lock.json
- e2e/package.json
- e2e/test/vitest-old-version/package-lock.json
- e2e/test/vitest-old-version/package.json
- packages/vitest-runner/.vscode/launch.json
- packages/vitest-runner/package-lock.json
- packages/vitest-runner/package.json
- packages/vitest-runner/schema/vitest-runner-options.json
- packages/vitest-runner/src/file-communicator.ts
- packages/vitest-runner/src/vitest-helpers.ts
- packages/vitest-runner/src/vitest-runner-options-with-stryker-options.ts
- packages/vitest-runner/src/vitest-test-runner.ts
- packages/vitest-runner/src/vitest-wrapper.ts
- packages/vitest-runner/test/integration/vitest-test-runner.it.spec.ts
- packages/vitest-runner/test/unit/file-communication.spec.ts
- packages/vitest-runner/test/unit/vitest-helpers.spec.ts
- packages/vitest-runner/test/unit/vitest-runner.spec.ts
- packages/vitest-runner/test/util/factories.ts
- packages/vitest-runner/testResources/simple-project/tests/add.spec.ts
- packages/vitest-runner/testResources/simple-project/vitest.browser.config.js
- packages/vitest-runner/testResources/simple-project/vitest.setup.ts
- Clearly state that the `@stryker-mutator/vitest-runner` doesn't support browser mode yet.
- Opt for [task metadata](https://vitest.dev/advanced/metadata.html) instead of file communication.
- Set minimal support `vitest` version to `0.31.2`, because of the task metadata support.
Fixes #4218
> fix(vitest): explicitly error when browser-mode is enabled

- packages/api/schema/stryker-core.json
- packages/core/test/unit/config/options-validator.spec.ts
- packages/core/test/unit/process/3-dry-run-executor.spec.ts
- stryker.parent.conf.json
Change the default of [`disableTypeChecks`](https://stryker-mutator.io/docs/stryker-js/configuration/#disabletypechecks-boolean--string) to `true`.
Closes #4204
> feat(type-checking): disable type check by default

- packages/core/src/fs/project-reader.ts
- packages/core/src/fs/project.ts
- packages/core/test/unit/fs/project-reader.spec.ts
Improve the warning shown when no files are marked for mutation.
```diff
- No files marked to be mutated, Stryker will perform a dry-run without actually mutating anything. You can configure the `mutate` property in your config file (or use `--mutate` via command line).
+Warning: No files found for mutation with the given glob expressions. As a result, a dry-run will be performed without actually modifying anything. If you intended to mutate files, please check and adjust the configuration. Current glob pattern(s) used: "{src,lib}/**/!(*.+(s|S)pec|*.+(t|T)est).+(cjs|mjs|js|ts|jsx|tsx|html|vue)", "!{src,lib}/**/__tests__/**/*.+(cjs|mjs|js|ts|jsx|tsx|html|vue)". To enable file mutation, consider configuring the `mutate` property in your configuration file or using the --mutate option via …
```
> fix(core): improve no-mutate warning

- e2e/test/mono-schema/package.json
- e2e/test/mono-schema/test/invalid.js
- e2e/test/mono-schema/test/tsconfig.json
- e2e/test/mono-schema/test/valid.js
- e2e/test/mono-schema/verify/package.json
- e2e/test/mono-schema/verify/verify.js
- packages/api/core.d.ts
Fix regression in `import('@stryker-mutator/api/core').PartialStrykerOptions` when using module resolution node.
Also, add an e2e test for it.
Fixes #4273
> fix(config): regression in import options

- packages/core/src/initializer/index.ts
- packages/core/src/initializer/initializer-tokens.ts
- packages/core/src/initializer/npm-client.ts
- packages/core/src/initializer/package-info.ts
- packages/core/src/initializer/stryker-initializer.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
Use https://registry.npmjs.com as a backend for any queries during init. This solves the caching problem and adds `vitest` and `tap` as test runners.
- https://registry.npmjs.com/-/v1/search?text=keywords:%40stryker-mutator%2Ftest-runner-plugin for test runner plugins
- https://registry.npmjs.com/%40stryker-mutator%2Fkarma-runner/latest to retrieve package.json
Closes #4288
> feat(init): use registry.npmjs.com for queries

- docs/vitest-runner.md
- packages/vitest-runner/schema/vitest-runner-options.json
- packages/vitest-runner/src/vitest-test-runner.ts
- packages/vitest-runner/test/integration/timeout-on-infinite-loop.it.spec.ts
- packages/vitest-runner/test/integration/vitest-test-runner.it.spec.ts
- packages/vitest-runner/testResources/deep-project/package.json
- packages/vitest-runner/testResources/deep-project/packages/app/src/math.js
- packages/vitest-runner/testResources/deep-project/packages/app/src/math.spec.js
- packages/vitest-runner/testResources/deep-project/resources/some-other.spec.js
- packages/vitest-runner/testResources/deep-project/vitest.config.ts
Add `"dir"` config option, which allows users to configure a `--dir <path>`.
Closes #4257
> feat(vitest-runner): add `"dir"` config option

- .github/workflows/publish.yml
A few months ago, npm introduced something called [npm provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/). Basically, it's a way to verify that a certain package was built on a certain commit with certain build steps, and not just a pinky-promise that some evildoer didn't publish it locally with some naughty code. All it takes is adding the option to the publish step, and npm/GH Actions will take care of the rest.
Right now, it doesn't do much other than showing a check on the npm page, and you can still publish new versions without provenance (it just won't show the check), but hopefully this will improve in the future.
> build: enable npm provenance

- packages/vitest-runner/src/vitest-test-runner.ts
JSDOM is not supported in vitest when using `singleThread = true` because it relies on being isolated.
With `singleThread = false` and `maxConcurrency = 1` this should be fixed. Concurrency should be set to 1 to prevent proces starvation.
Also fixed bug in the method readMutantCoverage `file.projectName` was undefined in the cases i tested so now its using `file.name`
Fixes #4336
> feat(vitest-runner): Support JSDOM

- packages/tap-runner/src/tap-test-runner.ts
- packages/tap-runner/test/integration/tap-test-runner.it.spec.ts
Added custom time calculation for a test run which is used when the tap result does not include the time spent.
Fixes #4331
> bug(tap-runnner): time spent not shown when tap result has no time spent

- docs/configuration.md
- packages/api/schema/stryker-core.json
- packages/core/src/reporters/clear-text-reporter.ts
- packages/core/test/helpers/producers.ts
- packages/core/test/unit/config/options-validator.spec.ts
- packages/core/test/unit/reporters/clear-text-reporter.spec.ts
Related issue: [here](https://github.com/stryker-mutator/stryker-js/issues/4209)
Implementation of additional configuration options for the clear-text reporter. These additions include the ability to enable/disable the three sections within the clear-text reporter that get printed: All tests, survived mutants, and score table.
Fixes #4209
> Implementation of additional configs for clear-text reporter

- packages/api/package.json
- packages/core/package.json
- packages/cucumber-runner/package.json
- packages/instrumenter/package.json
- packages/jasmine-runner/package.json
- packages/jest-runner/package.json
- packages/karma-runner/package.json
- packages/mocha-runner/package.json
- packages/tap-runner/package.json
- packages/typescript-checker/package.json
- packages/util/package.json
- packages/vitest-runner/package.json
Fix the problems reported in previous pull request https://github.com/stryker-mutator/stryker-js/pull/4405#issuecomment-1743831971: don't publish `dist/test/`, `dist/tsconfig.src.tsbuildinfo` and `dist/tsconfig.test.tsbuildinfo`.
---
- `api`: [diff between 7.1.1 and 7.2.0](https://diff.ecosyste.ms/diff?url_1=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fapi%2F-%2Fapi-7.1.1.tgz&url_2=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fapi%2F-%2Fapi-7.2.0.tgz) / [files in 7.2.0](https://www.npmjs.com/package/@stryker-mutator/api/v/7.2.0?activeTab=code)
- `core`: [diff](https://diff.ecosyste.ms/diff?url_1=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fcore%2F-%2Fcore-7.1.1.tgz&url_2=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fcore%2F-%2Fcore-7.2.0.tgz) / …
> fix: don't publish test and tsbuildinfo

- docs/config-file.md
Not sure why the newlines fix this, but it was failing: https://github.com/stryker-mutator/stryker-mutator.github.io/actions/runs/6405823874/job/17389198371
> chore: fix docs publishing

- packages/core/README.md
The `README.md` in stryker core said
`Stryker is written in TypeScript, so it is recommended to use Stryker as well to get the best developer experience.`
This should be
`Stryker is written in TypeScript, so it is recommended to use Typescript as well to get the best developer experience.`
> docs(core): recommended to use Typescript instead of "recommended to use Stryker"

- docs/configuration.md
- docs/disable-mutants.md
- docs/plugins.md
- e2e/test/ignore-project/stryker-plugins/ignorers/console-ignorer.js
- packages/api/schema/stryker-core.json
- packages/api/src/plugin/plugin-kind.ts
- packages/api/src/plugin/plugins.ts
- packages/core/src/process/2-mutant-instrumenter-executor.ts
- packages/core/test/integration/di/plugins.it.spec.ts
- packages/core/test/unit/process/2-mutant-instrumenter-executor.spec.ts
- packages/core/testResources/plugins/custom-plugins.js
- packages/instrumenter/src/transformers/ignorer-bookkeeper.ts
Small refactor in the naming of things
- `PluginKind.Ignorer` -> `PluginKind.Ignore`
- "ignorer plugin" -> "ignore-plugin"
Keep the name of "ignorers", because "ignore" itself has no plural. Also keep the name of the interface "Ignorer", because it is an ignorer object.
> refactor(ignore): rename `PluginKind.Ignorer` to `PluginKind.Ignore`

- packages/core/src/process/4-mutation-test-executor.ts
- packages/core/test/unit/process/4-mutation-test-executor.spec.ts
This should fix #4475 by short circuiting the test executor when no tests found and `allowEmpty=true` (same behaviour as `dryRunOnly`):
- prevent thresholds evaluation 
- avoid unnecessary run of the mutation executor (save some processing time)
> fix(core): short circuit test executor when no tests and allowEmpty

- packages/core/src/fs/project-reader.ts
- packages/core/test/unit/fs/project-reader.spec.ts
Added .next, .nuxt and .svelte-kit to the `ALWAYS_IGNORE` so it gets included in the ignorePattern
Closes #4571
> feat(core): Add .next, .nuxt and .svelte-kit to ignorePattern

- packages/core/src/child-proxy/child-process-proxy.ts
- packages/core/test/unit/child-proxy/child-process-proxy.spec.ts
Use a `Map` instead of an array, so we don't need to `delete` from the array, instead we can use `map.delete`.
See https://typescript-eslint.io/rules/no-array-delete/ on why it's a bad practice.
> refactor(child-process): use a map instead of an array

- docs/guides/angular.md
Document experimental jest support for Angular. It uses `ng test` to run unit testing as a build command in order to compile the unit tests. Then it runs the jest-runner with some custom config.
See #4184
> docs(angular): document experimental jest support

- packages/typescript-checker/src/tsconfig-helpers.ts
- packages/typescript-checker/test/unit/typescript-helpers.spec.ts
Stryker fails at launch when using `v5.4.0-beta` of TypeScript, displaying:
> `Error: @stryker-mutator/typescript-checker only supports typescript@3.6 or higher. Found typescript@5.4.0-beta`
This PR allows prerelease versions of TypeScript.
> feat(typescript-checker): support prerelease TypeScript versions

- packages/instrumenter/src/mutant-placers/expression-mutant-placer.ts
- packages/instrumenter/test/unit/mutant-placers/expression-mutant-placer.spec.ts
- packages/instrumenter/testResources/instrumenter/optional-chains.ts
- packages/instrumenter/testResources/instrumenter/optional-chains.ts.out.snap
Don't place mutants inside a delete expression.
Before:
```js
delete stryMutAct_9fa48(\\"11\\") ? myVariable[indexer] : (stryCov_9fa48(\\"11\\"), myVariable?.[indexer]);
```
After:
```js
stryMutAct_9fa48(\\"11\\") ? delete myVariable[indexer] : (stryCov_9fa48(\\"11\\"), delete myVariable?.[indexer]);
```
Fixes #4741
> fix(instrumenter): don't place mutants inside delete expressions

- packages/instrumenter/src/mutators/block-statement-mutator.ts
- packages/instrumenter/src/transformers/babel-transformer.ts
- packages/instrumenter/test/unit/mutators/block-statement-mutator.spec.ts
- packages/instrumenter/testResources/instrumenter/super-call.ts
- packages/instrumenter/testResources/instrumenter/super-call.ts.out.snap
Support constructors in TypeScript that have some code before the `super()` call and have constructor properties or initialized class properties. In such cases, the block statement mutator is not applied.
For more info, see #4744
Fixes #4744
> fix(instrumenter): support typescript constructors with code before `super()`

- packages/mocha-runner/src/lib-wrapper.ts
- packages/mocha-runner/src/mocha-adapter.ts
Fixes #4883
Update the `mocha-adapter.ts` of the mocha-runner to be compatible with v10.5.1 of Mocha. To preserve compatibility with earlier versions of Mocha, a runtime check for the return value of the affected Mocha API is added.
> fix(mocha-runner): compatibility with Mocha v10.5.1 and up

- package-lock.json
- packages/instrumenter/package.json
- packages/instrumenter/src/parsers/ts-parser.ts
- packages/instrumenter/test/integration/parsers.it.spec.ts.snap
- packages/instrumenter/testResources/parser/new-ts-features.ts
Support explicit resource management (`using` declarations) in TS files.
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html
Fixes #4876
> fix(instrumenter): support explicit resource management in TS

- packages/core/src/mutants/mutant-test-planner.ts
In a terminal on Windows the "." becomes part of the URL, so when you click it you will end up on a 404 page. That's why I suggest removing the "." at the end.
**Screenshot:**
> docs: Make link clickable

- packages/core/src/di/core-tokens.ts
- packages/core/src/initializer/index.ts
- packages/core/src/initializer/initializer-tokens.ts
- packages/core/src/initializer/npm-client.ts
- packages/core/src/initializer/npm-registry.ts
- packages/core/test/unit/initializer/npm-registry.spec.ts
- packages/core/test/unit/initializer/stryker-initializer.spec.ts
> feat(core): use user configured npm registry

- docs/configuration.md
Remove useless quote for description of [`clearTextReporter.allowColor`](https://stryker-mutator.io/docs/stryker-js/configuration/#cleartextreporter-cleartextoptions) in website.
> docs: remove useless quote

- docs/cucumber-runner.md
Update link to _peerDependencies in @stryker-mutator/cucumber-runner's package.json file_ in [_Cucumber Runner_](https://stryker-mutator.io/docs/stryker-js/cucumber-runner/#peer-dependencies) page.
> docs: update link to peerDependencies in cucumber-runner

- package-lock.json
- packages/core/package.json
- packages/core/src/utils/index.ts
- packages/core/src/utils/net-utils.ts
Remove the dependency on `get-port`. I forgot to remove it in #5111.
> refactor(logging): remove dependency on `get-port`

- packages/core/src/reporters/event-recorder-reporter.ts
- packages/core/src/sandbox/sandbox.ts
- packages/core/src/utils/file-utils.ts
- packages/core/src/utils/object-utils.ts
- packages/core/src/utils/temporary-directory.ts
- packages/core/test/integration/utils/file-utils.it.spec.ts
- packages/core/test/unit/reporters/event-recorder-reporter.spec.ts
- packages/core/test/unit/sandbox/sandbox.spec.ts
- packages/core/test/unit/utils/temporary-directory.spec.ts
Allow multiple runs of Stryker to share the same temp dir. This means that Stryker will _no longer remove the entire `.stryker-tmp` directory when it ran successfully (since other `sandbox-xxx` directories could be owned by other processes).
Note: this is implemented in preparation for the implementation of the mutation server protocol (#5086)
> feat(temp-dir): allow multiple instances to share the same temp-dir

- e2e/test/coverage-analysis/verify/verify.js
- packages/vitest-runner/src/vitest-test-runner.ts
- packages/vitest-runner/test/integration/browser-mode.it.spec.ts
When using browser environments in Vitest, browser screenshots on test failure are now enabled by default. This is unnecessary overhead when using StrykerJS, so this should be disabled instead.
Closes #5242
> fix(vitest-runner): Ensure no test failure screenshots from Vitest

- e2e/.npmrc
- package.json
Prevents errors like
```
npm error While resolving: karma-vite@1.0.5
npm error Found: vite@6.3.3
npm error node_modules/vite
npm error   dev vite@"6.3.3" from the root project
npm error   peer vite@"^5.0.3 || ^6.0.0" from @sveltejs/kit@2.20.7
npm error   node_modules/@sveltejs/kit
npm error     dev @sveltejs/kit@"2.20.7" from the root project
npm error     peer @sveltejs/kit@"^2.0.0" from @sveltejs/adapter-auto@6.0.0
npm error     node_modules/@sveltejs/adapter-auto
npm error       dev @sveltejs/adapter-auto@"6.0.0" from the root project
npm error   7 more (@sveltejs/vite-plugin-svelte, ...)
npm error
npm error Could not resolve dependency:
npm error peer vite@"2 || 3 || 4 || 5" from karma-vite@1.0.5
npm error node_modules/karma-vite
npm error   dev karma-vite@"1.0.5" from the root …
```
> chore(e2e): enforce `--force` when installing e2e

- docs/tap-runner.md
- packages/tap-runner/schema/tap-runner-options.json
Provide `--test-reporter=tap` as default in `tap.nodeArgs`, as the default `--test-reporter` changed in node 23 to 'spec', see https://github.com/nodejs/node/issues/58301
Fixes #5287
> feat(tap): provide `--test-reporter=tap` as default nodeArg

- packages/vitest-runner/src/stryker-setup.ts
- packages/vitest-runner/src/vitest-test-runner.ts
Support vitest's browser mode by copying the Stryker setup file locally to the project under test. That seems to be the only way to support browser mode.
Fixes #5305
> fix(vitest): copy stryker setup locally to support browser mode

- .github/workflows/ci.yml
Enable windows latest instead of 2025
> chore: enable windows latest

- package-lock.json
- packages/instrumenter/package.json
- packages/instrumenter/src/parsers/ts-parser.ts
Replace [`@babel/plugin-proposal-explicit-resource-management`](https://www.npmjs.com/package/@babel/plugin-proposal-explicit-resource-management) by [`@babel/plugin-transform-explicit-resource-management`](https://www.npmjs.com/package/@babel/plugin-transform-explicit-resource-management) as suggested by the deprecation warning of the former[^1]. This is a surface level replacement of the dependency (no related source code as adopted following this replacement nor the fact that the proposal has graduated). E.g., I noticed [`new-ts-features.ts`](https://github.com/stryker-mutator/stryker-js/blob/7270f111ff36d6b18669302f5702fd42f664d53e/packages/instrumenter/testResources/parser/new-ts-features.ts), where `using` should arguably no longer be considered a "new feature".
[^1]: "This proposal …
> chore: switch to `plugin-proposal-explicit-resource-management`

- .github/workflows/ci.yml
- docs/configuration.md
- tasks/download-incremental-reports.sh
- Always download the master incremental reports when renovate bot opens a PR
- Correctly document the default `dashboard.reportType`.
> chore: improve mutation testing download script
